import { useSyncExternalStore } from 'react';
import { hasAnyPermission, hasModule, isLocationAllowed, isTenantAllowed, PERMISSIONS } from './access.js';

const initialTasks = [
  { id: 'task-admission-1', title: 'Complete admission readiness review', owner: 'Intake team', due: 'Today · 11:30', status: 'Due today', sourceModule: 'admissions', sourceRecordType: 'Admission', sourceRecordId: 'adm-1001', clientId: 'client-1001', location: 'Greater Noida Centre', permissions: ['admissions.view'], module: 'admissions', destinationRoute: '/work/admissions', sensitivity: 'operational' },
  { id: 'task-mdt-1', title: 'Review treatment-plan action', owner: 'Care team', due: 'Today · 14:00', status: 'In progress', sourceModule: 'mdt', sourceRecordType: 'MDT', sourceRecordId: 'mdt-1001', clientId: 'client-1001', location: 'Greater Noida Centre', permissions: [PERMISSIONS.MDT_VIEW], module: 'mdt', destinationRoute: '/mdt', sensitivity: 'clinical' },
  { id: 'task-therapy-1', title: 'Confirm family follow-up', owner: 'Nisha Verma', due: 'Tomorrow · 09:00', status: 'Upcoming', sourceModule: 'therapy', sourceRecordType: 'TherapySession', sourceRecordId: 'session-1001', clientId: 'client-1001', location: 'Residential Unit A', permissions: [PERMISSIONS.THERAPY_VIEW], module: 'clinical', destinationRoute: '/therapy/sessions/session-1001', sensitivity: 'clinical' },
  { id: 'task-nursing-check-1001', title: 'Complete general wellbeing check', owner: 'Nisha Verma', due: 'Today · 10:00', status: 'Due', sourceModule: 'nursing', sourceRecordType: 'CareCheck', sourceRecordId: 'check-1001', clientId: 'client-1001', location: 'Residential Unit A', permissions: [PERMISSIONS.NURSING_VIEW], module: 'nursing', destinationRoute: '/clients/client-1001/nursing', sensitivity: 'clinical' }
];
const initialNotifications = [
  { id: 'notification-1', title: 'Consent expires in 7 days', detail: 'Client workspace · restricted record', category: 'consent', sourceModule: 'clients', location: 'Greater Noida Centre', permissions: [PERMISSIONS.CLIENTS_VIEW], destinationRoute: '/clients/client-1001', sensitivity: 'clinical' },
  { id: 'notification-2', title: 'New MDT action assigned', detail: 'Due today · Greater Noida Centre', category: 'task', sourceModule: 'mdt', location: 'Greater Noida Centre', permissions: [PERMISSIONS.MDT_VIEW], destinationRoute: '/mdt', sensitivity: 'clinical' },
  { id: 'notification-3', title: 'Home-care visit marked late', detail: 'Community service · Visit HC-2408', category: 'operations', sourceModule: 'home-care', location: 'Greater Noida Community Service', permissions: ['home-care.view'], module: 'home-care', destinationRoute: '/home-care/visits', sensitivity: 'operational' },
  { id: 'notification-ui6-1', title: 'Medication administration due', detail: 'Residential Unit A · MAR', category: 'medication', sourceModule: 'medication', location: 'Residential Unit A', permissions: [PERMISSIONS.MAR_VIEW], module: 'medication', destinationRoute: '/medication/mar', sensitivity: 'clinical' },
  { id: 'notification-ui6-2', title: 'Incident requires review', detail: 'Residential Unit A · supervisor queue', category: 'incident', sourceModule: 'residential', location: 'Residential Unit A', permissions: [PERMISSIONS.INCIDENT_REVIEW], module: 'residential', destinationRoute: '/incidents', sensitivity: 'clinical' }
];
const searchRecords = [
  { id: 'search-client-1', type: 'Client', label: 'Aarav Mehta', detail: 'MP-240018 · Residential Unit A', location: 'Residential Unit A', permissions: [PERMISSIONS.CLIENTS_VIEW], sensitivity: 'clinical', href: '/clients/client-1001' },
  { id: 'search-task-1', type: 'Task', label: 'Admission readiness review', detail: 'Due today · Intake team', location: 'Greater Noida Centre', permissions: ['admissions.view'], module: 'admissions', sensitivity: 'operational', href: '/work/tasks' },
  { id: 'search-location-1', type: 'Location', label: 'Greater Noida Centre', detail: 'Veda Wellness · Centre context', location: 'Greater Noida Centre', permissions: ['locations.manage', 'operations.manage', 'platform.manage'], sensitivity: 'administrative', href: '/admin/locations' },
  { id: 'search-resident-1', type: 'Resident', label: 'Aarav Mehta · Bed A-12', detail: 'Residential Unit A · In residence', location: 'Residential Unit A', permissions: [PERMISSIONS.NURSING_VIEW, PERMISSIONS.RESIDENTIAL_VIEW], sensitivity: 'clinical', href: '/clients/client-1001/nursing' },
  { id: 'search-mar-1', type: 'Medication', label: 'Sertraline · MAR', detail: 'Due · Residential Unit A', location: 'Residential Unit A', permissions: [PERMISSIONS.MAR_VIEW], module: 'medication', sensitivity: 'clinical', href: '/clients/client-1001/mar' },
  { id: 'search-bed-1', type: 'Bed', label: 'Residential Unit A · Bed A-14', detail: 'Available', tenant: 'Veda Wellness', location: 'Greater Noida Centre', permissions: [PERMISSIONS.BED_VIEW], module: 'facility', sensitivity: 'operational', href: '/facility/bed-board' },
  { id: 'search-client-centre-b', type: 'Client', label: 'Sofia Khan · Centre B', detail: 'MP-239999 · Centre B', tenant: 'Veda Wellness', location: 'Centre B', permissions: [PERMISSIONS.CLIENTS_VIEW], sensitivity: 'clinical', href: '/clients/client-1003' },
  { id: 'search-client-tenant-2', type: 'Client', label: 'Tara Singh · Tenant T2', detail: 'T2-1001 · Tenant T2 Centre', tenant: 'Tenant T2', location: 'Tenant T2 Centre', permissions: [PERMISSIONS.CLIENTS_VIEW], sensitivity: 'clinical', href: '/clients/client-2001' }
  , { id: 'search-homecare-visit-1001', type: 'Home Care', label: 'Aarav Mehta · Upcoming home visit', detail: '21 Sep 2026 · 10:30 · Wellbeing check', tenant: 'Veda Wellness', location: 'Greater Noida Community Service', permissions: [PERMISSIONS.HOMECARE_VIEW], module: 'home-care', sensitivity: 'operational', href: '/home-care/visits/hc-visit-1001' },
  { id: 'search-nutrition-plan-1001', type: 'Nutrition', label: 'Aarav Mehta · Active nutrition plan', detail: 'Review 27 Sep 2026 · Dietitian', tenant: 'Veda Wellness', location: 'Greater Noida Centre', permissions: [PERMISSIONS.NUTRITION_VIEW], module: 'nutrition', sensitivity: 'clinical', href: '/nutrition/plans/nutrition-plan-1001' },
  { id: 'search-discharge-plan-1001', type: 'Discharge', label: 'Aarav Mehta · Discharge readiness', detail: 'Target 30 Sep 2026 · adm-1001', tenant: 'Veda Wellness', location: 'Greater Noida Centre', permissions: [PERMISSIONS.DISCHARGE_VIEW], module: 'discharge', sensitivity: 'clinical', href: '/discharge/plans/discharge-plan-1001' },
  { id: 'search-aftercare-plan-1001', type: 'Aftercare', label: 'Aarav Mehta · Aftercare plan', detail: 'Discharged admission adm-1001', tenant: 'Veda Wellness', location: 'Greater Noida Centre', permissions: [PERMISSIONS.AFTERCARE_VIEW], module: 'aftercare', sensitivity: 'clinical', href: '/aftercare/plans/aftercare-plan-1001' }
];
const storageKey = 'medixpro-cross-cutting-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : { tasks: structuredClone(initialTasks), notifications: structuredClone(initialNotifications), revision: 0 }; } catch { return { tasks: structuredClone(initialTasks), notifications: structuredClone(initialNotifications), revision: 0 }; } }
let state = loadState();
const listeners = new Set(); const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
export function useCrossCuttingStore() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, () => state, () => state); }
export function canSeeRecord(access, record) { return hasAnyPermission(access, record.permissions || []) && (!record.module || hasModule(access, record.module)) && isTenantAllowed(access, record.tenant) && isLocationAllowed(access, record.location); }
export function getVisibleTasks(access) { return state.tasks.filter(task => canSeeRecord(access, task)); }
export function getVisibleNotifications(access) { const incidentReviewOpen = state.tasks.some(task => task.sourceRecordType === 'Incident' && task.status !== 'Completed'); return state.notifications.filter(notification => notification.status !== 'Completed' && (notification.id !== 'notification-ui6-2' || incidentReviewOpen) && canSeeRecord(access, notification)); }
export function getSearchResults(access) { return searchRecords.filter(record => canSeeRecord(access, record)); }
export function addTask(task) { state.tasks = [...state.tasks, task]; emit(); }
export function updateTaskStatus(sourceRecordId, status, completedBy = 'Nisha Verma', completedAt = 'Just now') { state.tasks = state.tasks.map(task => task.sourceRecordId === sourceRecordId ? { ...task, status, completedBy: status === 'Completed' ? completedBy : task.completedBy, completedAt: status === 'Completed' ? completedAt : task.completedAt } : task); emit(); }
export function updateNotificationStatus(sourceRecordId, status) { state.notifications = state.notifications.map(notification => notification.sourceRecordId === sourceRecordId ? { ...notification, status } : notification); emit(); }
export function addNotification(notification) { state.notifications = [...state.notifications, notification]; emit(); }
export function resetCrossCuttingStore() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = { tasks: structuredClone(initialTasks), notifications: structuredClone(initialNotifications), revision: 0 }; emit(); }