import { useSyncExternalStore } from 'react';
import { addNotification, addTask } from './crossCuttingStore.js';
import { isLocationAllowed, isTenantAllowed } from './access.js';

export const HOMECARE_STATUSES = Object.freeze({
  DRAFT: 'Draft', ACTIVE: 'Active', SUSPENDED: 'Suspended', COMPLETED: 'Completed', CANCELLED: 'Cancelled',
  SCHEDULED: 'Scheduled', CONFIRMED: 'Confirmed', IN_PROGRESS: 'InProgress', MISSED: 'Missed'
});

const tenantId = 'Veda Wellness';
const locationId = 'Greater Noida Community Service';
const clientId = 'client-1001';
const admissionId = 'adm-1001';
const staff = [
  { id: 'staff-hc-1', name: 'Nisha Verma', discipline: 'Nursing', location: locationId, availability: 'Available', skills: ['Medication observation', 'Wellbeing check'] },
  { id: 'staff-hc-2', name: 'Arjun Rao', discipline: 'Care coordination', location: locationId, availability: 'Available', skills: ['Care planning', 'Family coordination'] }
];
const initialState = {
  enrollments: [{ id: 'hc-enrollment-1001', tenantId, locationId, clientId, admissionId, programme: 'Community recovery support', status: HOMECARE_STATUSES.ACTIVE, effectiveStart: '20 Sep 2026', visitFrequency: '2 visits weekly', assignedTeam: ['staff-hc-1', 'staff-hc-2'], createdAt: '18 Sep 2026 · 10:00', createdBy: 'Arjun Rao', updatedAt: '18 Sep 2026 · 10:00', updatedBy: 'Arjun Rao' }],
  plans: [{ id: 'hc-plan-1001', enrollmentId: 'hc-enrollment-1001', clientId, admissionId, status: HOMECARE_STATUSES.ACTIVE, visitFrequency: '2 visits weekly', serviceTypes: ['Wellbeing check', 'Care coordination'], objectives: ['Maintain recovery routines at home'], specialInstructions: 'Confirm caregiver availability before each visit.', safetyConsiderations: 'Escalate acute deterioration through the canonical incident workflow.', treatmentPlanReference: 'client-1001', createdAt: '18 Sep 2026 · 10:15', createdBy: 'Arjun Rao', updatedAt: '18 Sep 2026 · 10:15', updatedBy: 'Arjun Rao' }],
  visits: [{ id: 'hc-visit-1001', enrollmentId: 'hc-enrollment-1001', planId: 'hc-plan-1001', tenantId, locationId, clientId, admissionId, service: 'Wellbeing check', scheduledDate: '21 Sep 2026', scheduledTime: '10:30', durationMinutes: 45, addressReference: 'Canonical client address · restricted', instructions: 'Review morning routine and caregiver questions.', assignedStaffId: 'staff-hc-1', status: HOMECARE_STATUSES.SCHEDULED, createdAt: '19 Sep 2026 · 12:00', createdBy: 'Arjun Rao', updatedAt: '19 Sep 2026 · 12:00', updatedBy: 'Arjun Rao', version: 1 }],
  documents: [],
  followUps: [],
  events: [{ id: 'homecare-enrollment:hc-enrollment-1001:started', clientId, admissionId, type: 'Home Care Enrollment Started', title: 'Home Care enrollment activated', date: '18 Sep 2026 · 10:00', recordId: 'hc-enrollment-1001' }],
  revision: 0
};

const storageKey = 'medixpro-home-care-domain-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState();
let sequence = 0;
const listeners = new Set();
const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
const nextId = prefix => { let id; do { id = `${prefix}-${++sequence}`; } while (Object.values(state).some(value => Array.isArray(value) && value.some(item => item?.id === id))); return id; };
const now = '20 Sep 2026 · 09:00';
function addEvent(event) { state.events = [...state.events, event]; }
function getEnrollment(id) { return state.enrollments.find(item => item.id === id); }
function getVisit(id) { return state.visits.find(item => item.id === id); }
function isActiveVisit(visit) { return visit && [HOMECARE_STATUSES.SCHEDULED, HOMECARE_STATUSES.CONFIRMED, HOMECARE_STATUSES.IN_PROGRESS].includes(visit.status); }

export function getHomeCareState() { return state; }
export function useHomeCareStore() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getHomeCareState, getHomeCareState); }
export function getHomeCareStaff() { return staff; }
export function getHomeCareEnrollmentForClient(id) { return state.enrollments.find(item => item.clientId === id && item.status !== HOMECARE_STATUSES.CANCELLED); }
export function getHomeCareVisibleRecords(access) { const allowed = item => isTenantAllowed(access, item.tenantId || item.tenant) && isLocationAllowed(access, item.locationId || item.location); return { enrollments: state.enrollments.filter(allowed), plans: state.plans.filter(item => item.enrollmentId && allowed(state.enrollments.find(enrollment => enrollment.id === item.enrollmentId) || {})), visits: state.visits.filter(allowed), followUps: state.followUps.filter(allowed) }; }

export function createHomeCareEnrollment(command) {
  if (!command?.clientId || !command?.programme || !command?.effectiveStart) return null;
  if (getHomeCareEnrollmentForClient(command.clientId)) return null;
  const enrollment = { id: nextId('hc-enrollment'), tenantId, locationId, clientId: command.clientId, admissionId: command.admissionId || null, programme: command.programme, status: HOMECARE_STATUSES.DRAFT, effectiveStart: command.effectiveStart, visitFrequency: command.visitFrequency || 'Weekly', assignedTeam: [], createdAt: now, createdBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator' };
  state.enrollments = [...state.enrollments, enrollment]; emit(); return enrollment.id;
}
export function activateHomeCareEnrollment(enrollmentId, command = {}) {
  const enrollment = getEnrollment(enrollmentId); if (!enrollment || enrollment.status !== HOMECARE_STATUSES.DRAFT) return false;
  state.enrollments = state.enrollments.map(item => item.id === enrollmentId ? { ...item, status: HOMECARE_STATUSES.ACTIVE, updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator' } : item);
  addEvent({ id: `homecare-enrollment:${enrollmentId}:started`, clientId: enrollment.clientId, admissionId: enrollment.admissionId, type: 'Home Care Enrollment Started', title: 'Home Care enrollment activated', date: now, recordId: enrollmentId }); emit(); return true;
}
export function updateHomeCarePlan(planId, patch, command = {}) { const plan = state.plans.find(item => item.id === planId); if (!plan || plan.status === HOMECARE_STATUSES.COMPLETED) return false; state.plans = state.plans.map(item => item.id === planId ? { ...item, ...patch, updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator' } : item); emit(); return true; }
export function createHomeCarePlan(command) { const enrollment = getEnrollment(command?.enrollmentId); if (!enrollment || !command?.objectives?.length) return null; const plan = { id: nextId('hc-plan'), enrollmentId: enrollment.id, clientId: enrollment.clientId, admissionId: enrollment.admissionId, status: HOMECARE_STATUSES.DRAFT, visitFrequency: command.visitFrequency || enrollment.visitFrequency, serviceTypes: command.serviceTypes || [], objectives: command.objectives, specialInstructions: command.specialInstructions || '', safetyConsiderations: command.safetyConsiderations || '', treatmentPlanReference: command.treatmentPlanReference || enrollment.clientId, createdAt: now, createdBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator' }; state.plans = [...state.plans, plan]; emit(); return plan.id; }
export function activateHomeCarePlan(planId, command = {}) { const plan = state.plans.find(item => item.id === planId); if (!plan || !plan.objectives.length) return false; state.plans = state.plans.map(item => item.id === planId ? { ...item, status: HOMECARE_STATUSES.ACTIVE, updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator' } : item); emit(); return true; }
export function scheduleHomeVisit(command) { const enrollment = getEnrollment(command?.enrollmentId); if (!enrollment || enrollment.status !== HOMECARE_STATUSES.ACTIVE || !command?.scheduledDate || !command?.scheduledTime || !command?.service) return null; const duplicate = state.visits.find(item => item.enrollmentId === enrollment.id && item.scheduledDate === command.scheduledDate && item.scheduledTime === command.scheduledTime && item.status !== HOMECARE_STATUSES.CANCELLED); if (duplicate) return duplicate.id; const visit = { id: nextId('hc-visit'), enrollmentId: enrollment.id, planId: command.planId || null, tenantId, locationId, clientId: enrollment.clientId, admissionId: enrollment.admissionId, service: command.service, scheduledDate: command.scheduledDate, scheduledTime: command.scheduledTime, durationMinutes: command.durationMinutes || 45, addressReference: 'Canonical client address · restricted', instructions: command.instructions || '', assignedStaffId: command.assignedStaffId || null, status: HOMECARE_STATUSES.SCHEDULED, createdAt: now, createdBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator', version: 1 }; state.visits = [...state.visits, visit]; if (!visit.assignedStaffId) addTask({ id: `task:${visit.id}:assignment`, title: 'Assign Home Care visit staff', owner: 'Home Care Coordinator', due: `${visit.scheduledDate} · ${visit.scheduledTime}`, status: 'Due', sourceModule: 'home-care', sourceRecordType: 'HomeCareVisit', sourceRecordId: visit.id, clientId: visit.clientId, tenant: tenantId, location: locationId, permissions: ['home-care.visit.schedule'], module: 'home-care', destinationRoute: `/home-care/visits/${visit.id}`, sensitivity: 'operational' }); emit(); return visit.id; }
export function assignHomeCareStaff(visitId, staffId, command = {}) { const visit = getVisit(visitId); const assignee = staff.find(item => item.id === staffId); if (!visit || !isActiveVisit(visit) || !assignee || assignee.location !== visit.locationId) return false; state.visits = state.visits.map(item => item.id === visitId ? { ...item, assignedStaffId: staffId, status: item.status === HOMECARE_STATUSES.SCHEDULED ? HOMECARE_STATUSES.CONFIRMED : item.status, updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator', version: item.version + 1 } : item); emit(); return true; }
export function startHomeVisit(visitId, command = {}) { const visit = getVisit(visitId); if (!visit || visit.status !== HOMECARE_STATUSES.CONFIRMED || !visit.assignedStaffId) return false; state.visits = state.visits.map(item => item.id === visitId ? { ...item, status: HOMECARE_STATUSES.IN_PROGRESS, startedAt: now, startedBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator', version: item.version + 1 } : item); emit(); return true; }
export function saveHomeVisitDraft(visitId, documentation, command = {}) { const visit = getVisit(visitId); if (!visit || visit.status !== HOMECARE_STATUSES.IN_PROGRESS) return false; state.documents = [...state.documents.filter(item => item.visitId !== visitId), { id: state.documents.find(item => item.visitId === visitId)?.id || nextId('hc-doc'), visitId, ...documentation, status: 'Draft', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator' }]; emit(); return true; }
export function completeHomeCareVisit(visitId, command = {}) { const visit = getVisit(visitId); const documentation = state.documents.find(item => item.visitId === visitId); if (!visit || visit.status !== HOMECARE_STATUSES.IN_PROGRESS || !documentation?.outcome || !documentation?.observations) return false; state.visits = state.visits.map(item => item.id === visitId ? { ...item, status: HOMECARE_STATUSES.COMPLETED, completedAt: now, completedBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator', version: item.version + 1 } : item); state.documents = state.documents.map(item => item.visitId === visitId ? { ...item, status: 'Finalized', finalizedAt: now, finalizedBy: command.actor || 'Home Care Coordinator' } : item); addEvent({ id: `homecare-visit:${visitId}:completed`, clientId: visit.clientId, admissionId: visit.admissionId, type: 'Home Care Visit Completed', title: `${visit.service} visit completed`, date: now, recordId: visitId }); emit(); return true; }
export function cancelHomeCareVisit(visitId, reason, command = {}) { const visit = getVisit(visitId); if (!visit || ![HOMECARE_STATUSES.SCHEDULED, HOMECARE_STATUSES.CONFIRMED].includes(visit.status) || !reason) return false; state.visits = state.visits.map(item => item.id === visitId ? { ...item, status: HOMECARE_STATUSES.CANCELLED, cancellationReason: reason, cancelledAt: now, cancelledBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator', version: item.version + 1 } : item); emit(); return true; }
export function markHomeCareVisitMissed(visitId, reason, command = {}) { const visit = getVisit(visitId); if (!visit || ![HOMECARE_STATUSES.SCHEDULED, HOMECARE_STATUSES.CONFIRMED].includes(visit.status) || !reason) return false; state.visits = state.visits.map(item => item.id === visitId ? { ...item, status: HOMECARE_STATUSES.MISSED, missedReason: reason, missedAt: now, missedBy: command.actor || 'Home Care Coordinator', updatedAt: now, updatedBy: command.actor || 'Home Care Coordinator', version: item.version + 1 } : item); const followUp = createHomeCareFollowUp({ visitId, clientId: visit.clientId, reason: 'Missed visit follow-up', tenantId, locationId, actor: command.actor }); addTask({ id: `task:${visitId}:missed`, title: 'Follow up missed Home Care visit', owner: 'Home Care Coordinator', due: 'Today', status: 'Due', sourceModule: 'home-care', sourceRecordType: 'HomeCareVisit', sourceRecordId: visitId, clientId: visit.clientId, tenant: tenantId, location: locationId, permissions: ['home-care.follow-up.manage'], module: 'home-care', destinationRoute: `/home-care/visits/${visitId}`, sensitivity: 'operational' }); emit(); return followUp; }
export function createHomeCareFollowUp(command) { if (!command?.visitId || state.followUps.some(item => item.visitId === command.visitId && item.status === 'Open')) return state.followUps.find(item => item.visitId === command.visitId)?.id || null; const item = { id: nextId('hc-followup'), visitId: command.visitId, clientId: command.clientId, tenantId: command.tenantId || tenantId, locationId: command.locationId || locationId, reason: command.reason, status: 'Open', createdAt: now, createdBy: command.actor || 'Home Care Coordinator' }; state.followUps = [...state.followUps, item]; emit(); return item.id; }
export function escalateHomeCareConcern(command) { if (!command?.visitId || !command?.concern) return null; const visit = getVisit(command.visitId); if (!visit) return null; const id = nextId('hc-escalation'); const item = { id, visitId: visit.id, clientId: visit.clientId, tenantId, locationId, concern: command.concern, status: 'Open', createdAt: now, createdBy: command.actor || 'Home Care Coordinator' }; state.followUps = [...state.followUps, item]; addTask({ id: `task:${id}`, title: 'Review Home Care safety escalation', owner: 'Care supervisor', due: 'Today', status: 'Due', sourceModule: 'home-care', sourceRecordType: 'HomeCareEscalation', sourceRecordId: id, clientId: visit.clientId, tenant: tenantId, location: locationId, permissions: ['home-care.escalate'], module: 'home-care', destinationRoute: `/home-care/escalations`, sensitivity: 'clinical' }); addNotification({ id: `notification:${id}`, title: 'Home Care safety escalation', detail: command.concern, category: 'home-care', sourceModule: 'home-care', sourceRecordType: 'HomeCareEscalation', sourceRecordId: id, clientId: visit.clientId, tenant: tenantId, location: locationId, permissions: ['home-care.escalate'], module: 'home-care', destinationRoute: '/home-care/escalations', sensitivity: 'clinical' }); emit(); return id; }
export function resetHomeCareStore() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); sequence = 0; emit(); }

export { staff as homeCareStaff };
