import { WORKSPACES, can } from './access.js';

const nav = [
  { id: 'platform-overview', label: 'Overview', icon: 'grid', href: '/platform/overview', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'workspace.view', module: 'platform' },
  { id: 'organizations', label: 'Organizations', icon: 'building', href: '/platform/organizations', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'tenant-onboarding', label: 'Tenant onboarding', icon: 'inbox', href: '/platform/onboarding', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'subscriptions', label: 'Subscriptions', icon: 'wallet', href: '/platform/subscriptions', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'saas-commercial', label: 'SaaS commercial', icon: 'wallet', href: '/super-admin/tenants', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.subscription.view', module: 'platform' },
  { id: 'platform-modules', label: 'Modules', icon: 'boxes', href: '/platform/modules', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'platform-access', label: 'Platform access', icon: 'users', href: '/platform/access', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'platform-configuration', label: 'Configuration', icon: 'sliders', href: '/platform/configuration', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'operations', label: 'Operations', icon: 'pulse', href: '/platform/operations', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'workspace.view', module: 'platform' },
  { id: 'integrations', label: 'Integrations', icon: 'activity', href: '/platform/integrations', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'platform' },
  { id: 'platform-security', label: 'Security', icon: 'shield', href: '/platform/security', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'platform.manage', module: 'security' },
  { id: 'ai-governance', label: 'AI governance', icon: 'sparkles', href: '/platform/ai-governance', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'ai.governance', module: 'ai-governance' },
  { id: 'platform-audit', label: 'Audit', icon: 'shield', href: '/platform/audit', workspace: WORKSPACES.PLATFORM_OPERATIONS, permission: 'audit.view', module: 'audit' },
  { id: 'admin-overview', label: 'Administration overview', icon: 'grid', href: '/admin/overview', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'organization', label: 'Organization', icon: 'building', href: '/admin/organization', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'locations', label: 'Locations', icon: 'pin', href: '/admin/locations', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'locations.manage', module: 'administration' },
  { id: 'users', label: 'Users & access', icon: 'users', href: '/admin/users', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'users.manage', module: 'administration' },
  { id: 'roles', label: 'Roles & permissions', icon: 'shield', href: '/admin/roles', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'users.manage', module: 'administration' },
  { id: 'module-access', label: 'Module access', icon: 'boxes', href: '/admin/module-access', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'configuration', label: 'Master configuration', icon: 'sliders', href: '/admin/configuration', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'configuration-centre', label: 'Configuration Centre', icon: 'sliders', href: '/admin/configuration', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'configuration.view', module: 'configuration' },
  { id: 'forms', label: 'Forms & templates', icon: 'clipboard', href: '/admin/forms', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'scheduling', label: 'Scheduling configuration', icon: 'calendar', href: '/admin/scheduling', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'notifications', label: 'Notifications', icon: 'bell', href: '/admin/notifications', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'admin-integrations', label: 'Integrations', icon: 'activity', href: '/admin/integrations', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'privacy-security', label: 'Privacy & security', icon: 'shield', href: '/admin/privacy-security', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'admin-audit', label: 'Audit', icon: 'shield', href: '/admin/audit', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'audit.view', module: 'audit' },
  { id: 'subscription-status', label: 'Subscription status', icon: 'wallet', href: '/admin/subscription', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.manage', module: 'administration' },
  { id: 'tenant-subscription', label: 'SaaS subscription', icon: 'wallet', href: '/settings/subscription', workspace: WORKSPACES.TENANT_ADMINISTRATION, permission: 'tenant.subscription.view', module: 'administration' },
  { id: 'centre-overview', label: 'Centre overview', icon: 'grid', href: '/work/centre-overview', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'operations.manage', module: 'operations' },
  { id: 'referrals', label: 'Referrals', icon: 'inbox', href: '/referrals', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'referrals.view', module: 'admissions' },
  { id: 'clients', label: 'Clients', icon: 'users', href: '/clients', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'clients.view' },
  { id: 'admissions', label: 'Admissions', icon: 'inbox', href: '/work/admissions', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'admissions.view', module: 'admissions' },
  { id: 'discharges', label: 'Discharges', icon: 'arrow', href: '/work/discharges', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'operations.manage', module: 'operations' },
  { id: 'occupancy', label: 'Bed board', icon: 'bed', href: '/facility/bed-board', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'facility.view', module: 'facility' },
  { id: 'schedule', label: 'Schedule', icon: 'calendar', href: '/work/schedule', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'operations.manage', module: 'operations' },
  { id: 'staff-assignments', label: 'Staff & assignments', icon: 'users', href: '/work/staff-assignments', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'operations.manage', module: 'operations' },
  { id: 'centre-tasks', label: 'Tasks', icon: 'check', href: '/work/tasks', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'tasks.view' },
  { id: 'centre-home-visits', label: 'Home-care visits', icon: 'calendar', href: '/home-care/visits', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'home-care.view', module: 'home-care' },
  { id: 'operational-alerts', label: 'Operational alerts', icon: 'alert', href: '/work/operational-alerts', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'operations.manage', module: 'operations' },
  { id: 'centre-reports', label: 'Reports', icon: 'receipt', href: '/work/reports', workspace: WORKSPACES.CENTRE_OPERATIONS, permission: 'operations.manage', module: 'operations' },
  { id: 'clinician-day', label: 'My day', icon: 'sun', href: '/work/my-day', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'workspace.view', module: 'clinical' },
  { id: 'clients', label: 'My clients', icon: 'users', href: '/work/clients', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'clients.view', module: 'clinical' },
  { id: 'clinical-work', label: 'Clinical work', icon: 'clipboard', href: '/work/clinical', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'clinical.work', module: 'clinical' },
  { id: 'mdt', label: 'MDT', icon: 'users', href: '/work/mdt', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'mdt.view', module: 'mdt' },
  { id: 'clinician-ai', label: 'AI intelligence', icon: 'sparkles', href: '/work/ai-intelligence', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'ai.assistance', module: 'ai-assistance' },
  { id: 'nutrition', label: 'Nutrition', icon: 'heart', href: '/nutrition/assessments', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'nutrition.view', module: 'nutrition' },
  { id: 'family', label: 'Family & caregivers', icon: 'users', href: '/family/contacts', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'family.view', module: 'family' },
  { id: 'telehealth', label: 'Telehealth', icon: 'activity', href: '/telehealth/schedule', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'telehealth.view', module: 'telehealth' },
  { id: 'discharge', label: 'Discharge', icon: 'arrow', href: '/discharge/worklist', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'discharge.view', module: 'discharge' },
  { id: 'aftercare', label: 'Aftercare', icon: 'calendar', href: '/aftercare/dashboard', workspace: WORKSPACES.CLINICIAN_WORKSPACE, permission: 'aftercare.view', module: 'aftercare' },
  { id: 'nursing-shift', label: 'My shift', icon: 'sun', href: '/nursing/my-shift', workspace: WORKSPACES.NURSING_WORKSPACE, permission: 'nursing.view', module: 'nursing' },
  { id: 'nursing-clients', label: 'Residents', icon: 'users', href: '/nursing/residents', workspace: WORKSPACES.NURSING_WORKSPACE, permission: 'clients.view', module: 'nursing' },
  { id: 'medication', label: 'MAR', icon: 'pill', href: '/medication/mar', workspace: WORKSPACES.NURSING_WORKSPACE, permission: 'mar.view', module: 'medication' },
  { id: 'observations', label: 'Observations', icon: 'activity', href: '/nursing/observations', workspace: WORKSPACES.NURSING_WORKSPACE, permission: 'observations.view', module: 'nursing' },
  { id: 'handover', label: 'Handover', icon: 'arrow', href: '/handover', workspace: WORKSPACES.NURSING_WORKSPACE, permission: 'handover.view', module: 'nursing' },
  { id: 'residential-shift', label: 'My shift', icon: 'sun', href: '/residential/my-shift', workspace: WORKSPACES.RESIDENTIAL_WORKSPACE, permission: 'residential.view', module: 'residential' },
  { id: 'residents', label: 'Residents', icon: 'users', href: '/residential/residents', workspace: WORKSPACES.RESIDENTIAL_WORKSPACE, permission: 'residents.view', module: 'residential' },
  { id: 'residential-tasks', label: 'Tasks & checks', icon: 'check', href: '/residential/tasks', workspace: WORKSPACES.RESIDENTIAL_WORKSPACE, permission: 'tasks.view', module: 'residential' },
  { id: 'residential-incidents', label: 'Incidents', icon: 'alert', href: '/residential/incidents', workspace: WORKSPACES.RESIDENTIAL_WORKSPACE, permission: 'incidents.create', module: 'residential' },
  { id: 'home-control', label: 'Control centre', icon: 'grid', href: '/home-care/control-centre', workspace: WORKSPACES.HOME_CARE_OPERATIONS, permission: 'home-care.view', module: 'home-care' },
  { id: 'home-visits', label: 'Visits', icon: 'calendar', href: '/home-care/visits', workspace: WORKSPACES.HOME_CARE_OPERATIONS, permission: 'home-care.view', module: 'home-care' },
  { id: 'caregivers', label: 'Caregivers', icon: 'users', href: '/home-care/caregivers', workspace: WORKSPACES.HOME_CARE_OPERATIONS, permission: 'caregivers.manage', module: 'home-care' },
  { id: 'home-escalations', label: 'Escalations', icon: 'alert', href: '/home-care/escalations', workspace: WORKSPACES.HOME_CARE_OPERATIONS, permission: 'escalations.view', module: 'home-care' },
  { id: 'billing-overview', label: 'Billing overview', icon: 'wallet', href: '/billing/overview', workspace: WORKSPACES.BILLING_OPERATIONS, permission: 'billing.view', module: 'billing' },
  { id: 'accounts', label: 'Accounts & invoices', icon: 'receipt', href: '/billing/accounts', workspace: WORKSPACES.BILLING_OPERATIONS, permission: 'billing.view', module: 'billing' },
  { id: 'billing-charges', label: 'Charges', icon: 'receipt', href: '/billing/charges', workspace: WORKSPACES.BILLING_OPERATIONS, permission: 'billing.view', module: 'billing' },
  { id: 'billing-payers', label: 'Payers & tariffs', icon: 'wallet', href: '/billing/payers', workspace: WORKSPACES.BILLING_OPERATIONS, permission: 'billing.view', module: 'billing' },
  { id: 'inventory-overview', label: 'Inventory overview', icon: 'boxes', href: '/inventory/overview', workspace: WORKSPACES.INVENTORY_OPERATIONS, permission: 'inventory.view', module: 'inventory' },
  { id: 'inventory-request', label: 'Request stock', icon: 'clipboard', href: '/inventory/request', workspace: WORKSPACES.INVENTORY_OPERATIONS, permission: 'inventory.request', module: 'inventory' },
  { id: 'stock', label: 'Stock & requests', icon: 'package', href: '/inventory/stock', workspace: WORKSPACES.INVENTORY_OPERATIONS, permission: 'inventory.view', module: 'inventory' },
  { id: 'inventory-items', label: 'Item master', icon: 'boxes', href: '/inventory/items', workspace: WORKSPACES.INVENTORY_OPERATIONS, permission: 'inventory.view', module: 'inventory' },
  { id: 'inventory-transfers', label: 'Transfers', icon: 'arrow', href: '/inventory/transfers', workspace: WORKSPACES.INVENTORY_OPERATIONS, permission: 'inventory.view', module: 'inventory' }
];

export function getEffectiveNavigation(access) {
  return nav.filter(item => item.workspace === access.workspace && can(access, item.permission, item.module));
}

export function getWorkspaceLabel(workspace) {
  return workspace.replaceAll('_', ' ').toLowerCase().replace(/(^|\s)\S/g, letter => letter.toUpperCase());
}

export { nav as navigationDefinitions };
