import { useSyncExternalStore } from 'react';
import { addTask } from './crossCuttingStore.js';
import { isLocationAllowed, isTenantAllowed } from './access.js';

export const UI10_STATUS = Object.freeze({ DRAFT: 'Draft', ACTIVE: 'Active', SUPERSEDED: 'Superseded', EXPIRED: 'Expired', REVOKED: 'Revoked', OPEN: 'Open', IN_PROGRESS: 'InProgress', RESOLVED: 'Resolved', COMPLETED: 'Completed', REQUESTED: 'Requested', READY: 'Ready' });
const tenantId = 'Veda Wellness';
const locationId = 'Greater Noida Centre';
const clientId = 'client-1001';
const admissionId = 'adm-1001';
const now = '20 Sep 2026 · 09:00';
const initialState = {
  documents: [{ id: 'document-1001', tenantId, locationId, clientId, admissionId, category: 'Discharge', documentType: 'Discharge Summary', title: 'Discharge summary', classification: 'Clinical', status: UI10_STATUS.ACTIVE, currentVersionId: 'document-version-1001-v1', effectiveDate: '30 Sep 2026', expiryDate: null, sourceModule: 'discharge', sourceType: 'discharge-plan', sourceId: 'discharge-plan-1001', createdAt: '18 Sep 2026 · 12:00', createdBy: 'Dr. Meera Shah' }],
  documentVersions: [{ id: 'document-version-1001-v1', documentId: 'document-1001', versionNumber: 1, fileName: 'discharge-summary.pdf', mimeType: 'application/pdf', status: UI10_STATUS.ACTIVE, reason: 'Initial registration', createdAt: '18 Sep 2026 · 12:00', createdBy: 'Dr. Meera Shah' }],
  consents: [{ id: 'consent-1001', tenantId, locationId, clientId, consentType: 'Information Sharing', scope: { caregiverId: 'caregiver-1001', purpose: 'Care coordination and discharge planning' }, effectiveFrom: '18 Sep 2026', expiresAt: '30 Sep 2026', status: UI10_STATUS.ACTIVE, capturedAt: '18 Sep 2026 · 10:00', capturedBy: 'Arjun Rao', sourceReference: 'consent-ui3-1001' }],
  complianceExceptions: [{ id: 'compliance-1001', tenantId, locationId, clientId, rule: 'Required document review', sourceReference: 'document-1001', severity: 'Medium', status: UI10_STATUS.OPEN, detectedAt: now, owner: 'Compliance team' }],
  auditEvents: [{ id: 'audit-1001', tenantId, locationId, actorId: 'arjun-rao', actor: 'Arjun Rao', action: 'Consent Captured', entityType: 'Consent', entityId: 'consent-1001', clientId, timestamp: '18 Sep 2026 · 10:00', sourceModule: 'consent', reason: 'Information sharing agreement' }, { id: 'audit-1002', tenantId, locationId, actorId: 'billing-user', actor: 'Billing User', action: 'Invoice Finalized', entityType: 'Invoice', entityId: 'invoice-1', clientId, timestamp: '20 Sep 2026 · 09:00', sourceModule: 'billing' }],
  reportRequests: [],
  revision: 0
};
const storageKey = 'medixpro-ui10-domain-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState(); let sequence = 0;
const listeners = new Set(); const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
const nextId = prefix => { let id; do { id = `${prefix}-${++sequence}`; } while (Object.values(state).some(value => Array.isArray(value) && value.some(item => item?.id === id))); return id; };
const scoped = (access, item) => isTenantAllowed(access, item.tenantId || item.tenant) && isLocationAllowed(access, item.locationId || item.location);
export function getUi10State() { return state; }
export function useUi10Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi10State, getUi10State); }
export function getUi10VisibleRecords(access) { return Object.fromEntries(Object.entries(state).filter(([, value]) => Array.isArray(value)).map(([key, value]) => [key, value.filter(item => scoped(access, item))])); }
export function registerDocument(command) { if (!command?.title || !command?.documentType || !command?.classification) return null; const id = nextId('document'); const versionId = nextId('document-version'); state.documents = [...state.documents, { id, tenantId, locationId, clientId: command.clientId || null, admissionId: command.admissionId || null, category: command.category || 'General', documentType: command.documentType, title: command.title, classification: command.classification, status: UI10_STATUS.ACTIVE, currentVersionId: versionId, effectiveDate: command.effectiveDate || now, expiryDate: command.expiryDate || null, sourceModule: command.sourceModule || 'documents', sourceType: command.sourceType || 'metadata', sourceId: command.sourceId || null, createdAt: now, createdBy: command.actor || 'User' }]; state.documentVersions = [...state.documentVersions, { id: versionId, documentId: id, versionNumber: 1, fileName: command.fileName || `${command.title}.metadata`, mimeType: command.mimeType || 'application/octet-stream', status: UI10_STATUS.ACTIVE, reason: 'Initial registration', createdAt: now, createdBy: command.actor || 'User' }]; emit(); return id; }
export function createDocumentVersion(documentId, command) { const doc = state.documents.find(item => item.id === documentId); if (!doc || !command?.fileName) return null; const current = state.documentVersions.filter(item => item.documentId === documentId).sort((a, b) => b.versionNumber - a.versionNumber)[0]; const versionId = nextId('document-version'); state.documentVersions = [...state.documentVersions.map(item => item.id === doc.currentVersionId ? { ...item, status: UI10_STATUS.SUPERSEDED } : item), { id: versionId, documentId, versionNumber: (current?.versionNumber || 0) + 1, fileName: command.fileName, mimeType: command.mimeType || 'application/octet-stream', status: UI10_STATUS.ACTIVE, reason: command.reason || 'New version', createdAt: now, createdBy: command.actor || 'User' }]; state.documents = state.documents.map(item => item.id === documentId ? { ...item, currentVersionId: versionId } : item); emit(); return versionId; }
export function captureConsent(command) { if (!command?.clientId || !command?.consentType || !command?.scope) return null; const id = nextId('consent'); state.consents = [...state.consents, { id, tenantId, locationId, clientId: command.clientId, consentType: command.consentType, scope: command.scope, effectiveFrom: command.effectiveFrom || now, expiresAt: command.expiresAt || null, status: UI10_STATUS.ACTIVE, capturedAt: now, capturedBy: command.actor || 'User', sourceReference: command.sourceReference || null }]; state.auditEvents = [...state.auditEvents, { id: nextId('audit'), tenantId, locationId, actor: command.actor || 'User', action: 'Consent Captured', entityType: 'Consent', entityId: id, clientId: command.clientId, timestamp: now, sourceModule: 'consent' }]; emit(); return id; }
export function revokeConsent(id, reason, command = {}) { const item = state.consents.find(value => value.id === id); if (!item || item.status !== UI10_STATUS.ACTIVE || !reason) return false; state.consents = state.consents.map(value => value.id === id ? { ...value, status: UI10_STATUS.REVOKED, revokedAt: now, revokedBy: command.actor || 'User', revocationReason: reason } : value); state.auditEvents = [...state.auditEvents, { id: nextId('audit'), tenantId, locationId, actor: command.actor || 'User', action: 'Consent Revoked', entityType: 'Consent', entityId: id, clientId: item.clientId, timestamp: now, sourceModule: 'consent', reason }]; emit(); return true; }
export function assignComplianceException(id, command = {}) { const item = state.complianceExceptions.find(value => value.id === id); if (!item || item.status === UI10_STATUS.RESOLVED) return false; mutateCompliance(id, { status: UI10_STATUS.IN_PROGRESS, owner: command.owner || 'Compliance team' }); return true; }
export function resolveComplianceException(id, command = {}) { const item = state.complianceExceptions.find(value => value.id === id); if (!item || item.status === UI10_STATUS.RESOLVED || !command?.resolution) return false; mutateCompliance(id, { status: UI10_STATUS.RESOLVED, resolution: command.resolution, resolvedAt: now, resolvedBy: command.actor || 'Compliance team' }); return true; }
function mutateCompliance(id, patch) { state.complianceExceptions = state.complianceExceptions.map(item => item.id === id ? { ...item, ...patch } : item); emit(); }
export function requestReportExport(command = {}) { if (!command.reportType) return null; const id = nextId('report'); const item = { id, tenantId, locationId, reportType: command.reportType, filters: command.filters || {}, status: UI10_STATUS.REQUESTED, requestedAt: now, requestedBy: command.actor || 'User' }; state.reportRequests = [...state.reportRequests, item]; addTask({ id: `task:${id}`, title: `Prepare ${command.reportType} report`, owner: command.actor || 'User', due: 'Today', status: 'Due', sourceModule: 'reports', sourceRecordType: 'ReportRequest', sourceRecordId: id, tenant: tenantId, location: locationId, permissions: ['reports.export'], module: 'reports', destinationRoute: '/reports/catalogue', sensitivity: 'operational' }); emit(); return id; }
export function resetUi10Store() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); sequence = 0; emit(); }
