import { useSyncExternalStore } from 'react';
import { addTask } from './crossCuttingStore.js';
import { getUi3State } from './ui3Store.js';
import { getUi6State, recordObservation } from './ui6Store.js';
import { isLocationAllowed, isTenantAllowed } from './access.js';

export const AI_STATUS = Object.freeze({ REQUESTED: 'Requested', PROCESSING: 'Processing', READY: 'ReadyForReview', PARTIAL: 'PartiallyAccepted', ACCEPTED: 'Accepted', REJECTED: 'Rejected', FAILED: 'Failed', SUPERSEDED: 'Superseded' });
const tenantId = 'Veda Wellness';
const locationId = 'Greater Noida Centre';
const clientId = 'client-1001';
const admissionId = 'adm-1001';
const now = '20 Sep 2026 · 09:00';
const initialState = { requests: [], recommendations: [], audit: [], revision: 0 };
const storageKey = 'medixpro-ui11-domain-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState(); let sequence = 0;
const listeners = new Set(); const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
const nextId = prefix => `${prefix}-${++sequence}`;
const scoped = (access, item) => isTenantAllowed(access, item.tenantId || item.tenant) && isLocationAllowed(access, item.locationId || item.location);
export function getUi11State() { return state; }
export function useUi11Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi11State, getUi11State); }
export function buildAuthorizedAiContext(access, command = {}) { if (!access || !command.clientId || !scoped(access, { tenantId, locationId })) return null; const source = []; const manifest = []; const client = getUi3State().clients.find(item => item.id === command.clientId); if (client && access.permissions.includes('clients.view')) { source.push({ type: 'Client', id: client.id }); manifest.push('Client demographics — Included'); } if (command.purpose === 'current-care-summary' && access.permissions.includes('clinical.view')) { source.push({ type: 'Admission', id: command.admissionId || admissionId }); manifest.push('Active admission — Included'); manifest.push('Treatment plan — Included'); manifest.push('Restricted therapy narrative — Excluded'); } if (command.purpose === 'nursing-draft' && access.permissions.includes('nursing.view')) { const observations = getUi6State().observations.filter(item => item.clientId === command.clientId); source.push(...observations.map(item => ({ type: 'Observation', id: item.id }))); manifest.push('Recent nursing observations — Included'); manifest.push('Billing — Excluded'); } return { tenantId, locationId, clientId: command.clientId, admissionId: command.admissionId || admissionId, purpose: command.purpose, source, manifest }; }
export function requestAiAssistance(access, command = {}) { if (!access?.permissions.includes('ai.use')) return null; const context = buildAuthorizedAiContext(access, command); if (!context) return null; const requestId = nextId('ai-request'); const recommendationId = nextId('ai-recommendation'); const fail = command.simulateFailure; const request = { id: requestId, tenantId, locationId, clientId: context.clientId, admissionId: context.admissionId, requestedBy: access.label, requestedAt: now, workspace: command.workspace || 'Client 360', purpose: command.purpose || 'current-care-summary', authorizedContextReferences: context.source, status: fail ? AI_STATUS.FAILED : AI_STATUS.REQUESTED, manifest: context.manifest }; const content = command.purpose === 'nursing-draft' ? { sections: [{ id: 'observation', label: 'Observation draft', text: 'Client appears engaged and comfortable during the documented wellbeing context.', accepted: false }, { id: 'followup', label: 'Follow-up draft', text: 'Continue structured observation and review outstanding care tasks.', accepted: false }] } : { sections: [{ id: 'summary', label: 'Current care summary', text: 'Aarav Mehta has an active residential rehabilitation episode with treatment, nursing, medication, accommodation and aftercare context available for authorized review.', accepted: false }, { id: 'concerns', label: 'Review considerations', text: 'Review documented tasks and readiness items before the next care transition.', accepted: false }] }; const recommendation = { id: recommendationId, requestId, tenantId, locationId, clientId: context.clientId, admissionId: context.admissionId, type: command.type || 'Summary', status: fail ? AI_STATUS.FAILED : AI_STATUS.READY, generatedAt: now, content, sourceReferences: context.source, reviewedBy: null, reviewedAt: null, decision: null, appliedCommandReference: null, contextFingerprint: context.source.map(item => `${item.type}:${item.id}`).join('|') }; state.requests = [...state.requests, request]; state.recommendations = [...state.recommendations, recommendation]; emit(); return { requestId, recommendationId }; }
export function retryAiRequest(access, requestId) { const request = state.requests.find(item => item.id === requestId); if (!request || request.status !== AI_STATUS.FAILED) return null; return requestAiAssistance(access, { clientId: request.clientId, admissionId: request.admissionId, purpose: request.purpose, workspace: request.workspace }); }
export function reviewAiRecommendation(id, decision, acceptedSectionIds = [], command = {}) { const item = state.recommendations.find(value => value.id === id); if (!item || ![AI_STATUS.READY, AI_STATUS.PARTIAL].includes(item.status) || !['Accepted', 'PartiallyAccepted', 'Rejected'].includes(decision)) return false; const sections = item.content.sections.map(section => ({ ...section, accepted: acceptedSectionIds.includes(section.id) })); state.recommendations = state.recommendations.map(value => value.id === id ? { ...value, content: { ...value.content, sections }, status: decision === 'Accepted' ? AI_STATUS.ACCEPTED : decision, reviewedBy: command.actor || 'Clinician', reviewedAt: now, decision } : value); state.audit = [...state.audit, { id: nextId('ai-audit'), action: `AI Recommendation ${decision}`, requestId: item.requestId, recommendationId: id, actor: command.actor || 'Clinician', timestamp: now }]; emit(); return true; }
export function applyAiRecommendation(id, command = {}) { const item = state.recommendations.find(value => value.id === id); if (!item || ![AI_STATUS.ACCEPTED, AI_STATUS.PARTIAL].includes(item.status) || item.appliedCommandReference) return false; const accepted = item.content.sections.filter(section => section.accepted); if (!accepted.length || command.currentContextFingerprint && command.currentContextFingerprint !== item.contextFingerprint) return false; if (item.type === 'Nursing Draft') { recordObservation(item.clientId, { type: 'AI-assisted nursing draft', value: accepted.map(section => section.text).join(' '), note: 'Human-reviewed AI-assisted draft.' }); } item.appliedCommandReference = `canonical:${item.type}:${item.clientId}:${now}`; item.humanEdited = Boolean(command.humanEdited); state.audit = [...state.audit, { id: nextId('ai-audit'), action: 'AI Recommendation Applied', requestId: item.requestId, recommendationId: id, actor: command.actor || 'Clinician', timestamp: now, canonicalCommandReference: item.appliedCommandReference }]; emit(); return true; }
export function resetUi11Store() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); sequence = 0; emit(); }
