import { useSyncExternalStore } from 'react';
import { can, isLocationAllowed, isTenantAllowed, PERMISSIONS } from './access.js';
import { registerConfiguredBed } from './ui6Store.js';
import { registerConfiguredItem } from './ui9Store.js';

export const UI12_STATUS = Object.freeze({ DRAFT: 'Draft', ACTIVE: 'Active', INACTIVE: 'Inactive', SUPERSEDED: 'Superseded' });
const tenantId = 'Veda Wellness';
const locationId = 'Greater Noida Centre';
const now = '20 Sep 2026 · 09:00';
const initialState = {
  locations: [{ id: 'location-veda-noida', tenantId, name: locationId, code: 'GNC', status: UI12_STATUS.ACTIVE }, { id: 'location-veda-delhi', tenantId, name: 'Delhi Centre', code: 'DEL', status: UI12_STATUS.ACTIVE }],
  units: [{ id: 'unit-residential-a', tenantId, locationId: 'location-veda-noida', code: 'UNIT-A', name: 'Residential Unit A', type: 'Residential', status: UI12_STATUS.ACTIVE }],
  rooms: [{ id: 'room-1001', tenantId, locationId, unitId: 'unit-residential-a', code: 'ROOM-1', name: 'Room 1', category: 'Residential', capacity: 2, status: UI12_STATUS.ACTIVE }],
  beds: [{ id: 'bed-1001', tenantId, locationId, roomId: 'room-1001', code: 'A-12', label: 'A-12', category: 'Standard', status: UI12_STATUS.ACTIVE }, { id: 'bed-1002', tenantId, locationId, roomId: 'room-1001', code: 'A-14', label: 'A-14', category: 'Standard', status: UI12_STATUS.ACTIVE }],
  programmes: [{ id: 'programme-residential', tenantId, code: 'RES', name: 'Residential rehabilitation', serviceLine: 'Residential', status: UI12_STATUS.ACTIVE }, { id: 'programme-home-care', tenantId, code: 'HC', name: 'Home Care', serviceLine: 'Home Care', status: UI12_STATUS.ACTIVE }],
  services: [{ id: 'service-room-private-day', tenantId, code: 'ROOM-PRIVATE-DAY', name: 'Private room per day', category: 'Accommodation', unit: 'day', status: UI12_STATUS.ACTIVE }, { id: 'service-therapy-individual', tenantId, code: 'TH-IND', name: 'Individual therapy session', category: 'Therapy', unit: 'session', status: UI12_STATUS.ACTIVE }],
  payers: [{ id: 'payer-self-pay', tenantId, code: 'SELF', name: 'Self Pay', type: 'Self Pay', status: UI12_STATUS.ACTIVE }],
  tariffs: [{ id: 'tariff-standard-self-pay', tenantId, locationId, name: 'Standard Self Pay', payerId: 'payer-self-pay', effectiveFrom: '20 Sep 2026', effectiveTo: null, status: UI12_STATUS.ACTIVE, lines: [{ id: 'tariff-line-room-private', serviceId: 'service-room-private-day', rate: 2500, currency: 'INR', unit: 'day', status: UI12_STATUS.ACTIVE }] }],
  items: [{ id: 'item-med-1001', tenantId, code: 'MED-SER-50', name: 'Sertraline 50 mg', category: 'Medication', unitOfMeasure: 'tablet', reorderLevel: 20, batchTrackingRequired: true, expiryTrackingRequired: true, status: UI12_STATUS.ACTIVE }, { id: 'item-cons-1001', tenantId, code: 'CONS-GLOVES', name: 'Nitrile gloves', category: 'Consumable', unitOfMeasure: 'box', reorderLevel: 10, batchTrackingRequired: false, expiryTrackingRequired: false, status: UI12_STATUS.ACTIVE }],
  audit: [],
  revision: 0
};
const storageKey = 'medixpro-ui12-master-data-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState();
state.locations = state.locations || structuredClone(initialState.locations);
let sequence = 0;
let bedCapacityValidator = null;
const listeners = new Set();
const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
const nextId = prefix => `${prefix}-${++sequence}`;
const locationScope = value => value === 'location-veda-noida' ? locationId : value === 'location-veda-delhi' ? 'Delhi Centre' : value;
const scoped = (access, item) => isTenantAllowed(access, item.tenantId) && isLocationAllowed(access, locationScope(item.locationId));
const authorized = (access, permission, item = {}) => Boolean(access && can(access, permission, 'configuration') && scoped(access, { tenantId: item.tenantId || tenantId, locationId: item.locationId || locationId }));
function audit(action, entityType, entityId, actor = 'Administrator', reason = null) { state.audit = [...state.audit, { id: nextId('config-audit'), action, entityType, entityId, actor, timestamp: now, tenantId, locationId, reason }]; }
function duplicate(list, field, value, exceptId) { return list.some(item => item[field] === value && item.id !== exceptId && item.status !== UI12_STATUS.INACTIVE); }
export function getUi12State() { return state; }
export function setBedCapacityValidator(validator) { bedCapacityValidator = validator; }
function capacityAllows(locationId, additionalActiveBeds = 0) { if (!bedCapacityValidator) return true; const activeBeds = state.beds.filter(item => item.locationId === locationId && item.status === UI12_STATUS.ACTIVE).length; return bedCapacityValidator(locationId, activeBeds + additionalActiveBeds); }
export function createLocation(command = {}) { if (!command.tenantId || !command.name || state.locations.some(item => item.tenantId === command.tenantId && item.code === command.code)) return null; const item = { id: command.id || nextId('location'), tenantId: command.tenantId, name: command.name, code: command.code || command.name.replaceAll(' ', '-').toUpperCase(), status: UI12_STATUS.ACTIVE }; state.locations = [...state.locations, item]; emit(); return item.id; }
export function useUi12Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi12State, getUi12State); }
export function getUi12VisibleRecords(access) { return Object.fromEntries(Object.entries(state).filter(([, value]) => Array.isArray(value)).map(([key, value]) => [key, value.filter(item => !['audit'].includes(key) ? scoped(access, item) : scoped(access, item))])); }
export function createUnit(access, command = {}) { if (!authorized(access, PERMISSIONS.FACILITY_CONFIGURE) || !command.code || !command.name || duplicate(state.units, 'code', command.code)) return null; const item = { id: nextId('unit'), tenantId, locationId: command.locationId || locationId, code: command.code, name: command.name, type: command.type || 'Unit', description: command.description || '', status: UI12_STATUS.ACTIVE }; state.units = [...state.units, item]; audit('Unit Created', 'Unit', item.id, command.actor); emit(); return item.id; }
export function updateUnit(access, id, command = {}) { const item = state.units.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.FACILITY_CONFIGURE, item) || (command.code && duplicate(state.units, 'code', command.code, id))) return false; state.units = state.units.map(value => value.id === id ? { ...value, ...command } : value); audit('Unit Updated', 'Unit', id, command.actor); emit(); return true; }
export function setUnitStatus(access, id, status, command = {}) { const item = state.units.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.FACILITY_CONFIGURE, item) || !command.reason) return false; state.units = state.units.map(value => value.id === id ? { ...value, status } : value); audit(status === UI12_STATUS.ACTIVE ? 'Unit Reactivated' : 'Unit Deactivated', 'Unit', id, command.actor, command.reason); emit(); return true; }
export function createRoom(access, command = {}) { const unit = state.units.find(item => item.id === command.unitId); const requestedLocation = command.locationId || unit?.locationId; if (!authorized(access, PERMISSIONS.ROOM_MANAGE, { ...command, locationId: requestedLocation === 'location-veda-noida' ? locationId : requestedLocation }) || !unit || unit.tenantId !== tenantId || unit.locationId !== requestedLocation || !command.code || !command.name || duplicate(state.rooms, 'code', command.code)) return null; const item = { id: nextId('room'), tenantId, locationId: unit.locationId, unitId: unit.id, code: command.code, name: command.name, category: command.category || 'Residential', capacity: Number(command.capacity || 1), status: UI12_STATUS.ACTIVE }; state.rooms = [...state.rooms, item]; audit('Room Created', 'Room', item.id, command.actor); emit(); return item.id; }
export function updateRoom(access, id, command = {}) { const item = state.rooms.find(value => value.id === id); const unit = state.units.find(value => value.id === (command.unitId || item?.unitId)); if (!item || !unit || !authorized(access, PERMISSIONS.ROOM_MANAGE, item) || unit.tenantId !== item.tenantId || (command.code && duplicate(state.rooms, 'code', command.code, id))) return false; state.rooms = state.rooms.map(value => value.id === id ? { ...value, ...command, unitId: unit.id } : value); audit('Room Updated', 'Room', id, command.actor); emit(); return true; }
export function deactivateRoom(access, id, command = {}) { const item = state.rooms.find(value => value.id === id); const hasActiveBed = state.beds.some(bed => bed.roomId === id && bed.status === UI12_STATUS.ACTIVE); if (!item || !authorized(access, PERMISSIONS.ROOM_MANAGE, item) || hasActiveBed || !command.reason) return false; state.rooms = state.rooms.map(value => value.id === id ? { ...value, status: UI12_STATUS.INACTIVE } : value); audit('Room Deactivated', 'Room', id, command.actor, command.reason); emit(); return true; }
export function reactivateRoom(access, id, command = {}) { const item = state.rooms.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.ROOM_MANAGE, item) || !command.reason) return false; state.rooms = state.rooms.map(value => value.id === id ? { ...value, status: UI12_STATUS.ACTIVE } : value); audit('Room Reactivated', 'Room', id, command.actor, command.reason); emit(); return true; }
export function createBed(access, command = {}) { const room = state.rooms.find(item => item.id === command.roomId); const unit = state.units.find(item => item.id === room?.unitId); if (!authorized(access, PERMISSIONS.BED_CONFIGURE, command) || !room || room.status !== UI12_STATUS.ACTIVE || room.tenantId !== tenantId || !command.code || duplicate(state.beds, 'code', command.code) || !capacityAllows(room.locationId, 1)) return null; const item = { id: command.id || nextId('configured-bed'), tenantId, locationId: room.locationId, roomId: room.id, room: room.name, unit: unit?.name || 'Configured unit', code: command.code, label: command.label || command.code, category: command.category || 'Standard', status: UI12_STATUS.ACTIVE }; state.beds = [...state.beds, item]; registerConfiguredBed(item); audit('Bed Created', 'Bed', item.id, command.actor); emit(); return item.id; }
export function updateBed(access, id, command = {}) { const item = state.beds.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.BED_CONFIGURE, item) || (command.code && duplicate(state.beds, 'code', command.code, id)) || (command.status === UI12_STATUS.ACTIVE && item.status !== UI12_STATUS.ACTIVE && !capacityAllows(item.locationId, 1))) return false; state.beds = state.beds.map(value => value.id === id ? { ...value, ...command } : value); audit('Bed Updated', 'Bed', id, command.actor); emit(); return true; }
export function deactivateBed(access, id, command = {}) { const item = state.beds.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.BED_CONFIGURE, item) || !command.reason) return false; const operational = (() => { try { return registerConfiguredBed(item, { checkOnly: true }); } catch { return null; } })(); if (operational?.status === 'Occupied') return false; state.beds = state.beds.map(value => value.id === id ? { ...value, status: UI12_STATUS.INACTIVE } : value); audit('Bed Deactivated', 'Bed', id, command.actor, command.reason); emit(); return true; }
export function reactivateBed(access, id, command = {}) { const item = state.beds.find(value => value.id === id); const room = state.rooms.find(value => value.id === item?.roomId); if (!item || !room || room.status !== UI12_STATUS.ACTIVE || !authorized(access, PERMISSIONS.BED_CONFIGURE, item) || !command.reason || !capacityAllows(item.locationId, 1)) return false; state.beds = state.beds.map(value => value.id === id ? { ...value, status: UI12_STATUS.ACTIVE } : value); audit('Bed Reactivated', 'Bed', id, command.actor, command.reason); emit(); return true; }
export function createProgramme(access, command = {}) { if (!authorized(access, PERMISSIONS.PROGRAMME_MANAGE, command) || !command.code || !command.name || duplicate(state.programmes, 'code', command.code)) return null; const item = { id: nextId('programme'), tenantId, code: command.code, name: command.name, serviceLine: command.serviceLine || 'Other', description: command.description || '', status: UI12_STATUS.ACTIVE }; state.programmes = [...state.programmes, item]; audit('Programme Created', 'Programme', item.id, command.actor); emit(); return item.id; }
export function updateProgramme(access, id, command = {}) { const item = state.programmes.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.PROGRAMME_MANAGE, item) || (command.code && duplicate(state.programmes, 'code', command.code, id))) return false; state.programmes = state.programmes.map(value => value.id === id ? { ...value, ...command } : value); audit('Programme Updated', 'Programme', id, command.actor); emit(); return true; }
export function setProgrammeStatus(access, id, status, command = {}) { const item = state.programmes.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.PROGRAMME_MANAGE, item) || !command.reason) return false; state.programmes = state.programmes.map(value => value.id === id ? { ...value, status } : value); audit(status === UI12_STATUS.ACTIVE ? 'Programme Reactivated' : 'Programme Deactivated', 'Programme', id, command.actor, command.reason); emit(); return true; }
export function createServiceDefinition(access, command = {}) { if (!authorized(access, PERMISSIONS.SERVICE_MANAGE, command) || !command.code || !command.name || duplicate(state.services, 'code', command.code)) return null; const item = { id: nextId('service'), tenantId, code: command.code, name: command.name, category: command.category || 'Other', unit: command.unit || 'each', status: UI12_STATUS.ACTIVE }; state.services = [...state.services, item]; audit('Service Created', 'Service', item.id, command.actor); emit(); return item.id; }
export function updateServiceDefinition(access, id, command = {}) { const item = state.services.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.SERVICE_MANAGE, item) || (command.code && duplicate(state.services, 'code', command.code, id))) return false; state.services = state.services.map(value => value.id === id ? { ...value, ...command } : value); audit('Service Updated', 'Service', id, command.actor); emit(); return true; }
export function deactivateServiceDefinition(access, id, command = {}) { const item = state.services.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.SERVICE_MANAGE, item) || !command.reason) return false; state.services = state.services.map(value => value.id === id ? { ...value, status: UI12_STATUS.INACTIVE } : value); audit('Service Deactivated', 'Service', id, command.actor, command.reason); emit(); return true; }
export function reactivateServiceDefinition(access, id, command = {}) { const item = state.services.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.SERVICE_MANAGE, item) || !command.reason) return false; state.services = state.services.map(value => value.id === id ? { ...value, status: UI12_STATUS.ACTIVE } : value); audit('Service Reactivated', 'Service', id, command.actor, command.reason); emit(); return true; }
export function createPayer(access, command = {}) { if (!authorized(access, PERMISSIONS.PAYER_MANAGE, command) || !command.code || !command.name || duplicate(state.payers, 'code', command.code)) return null; const item = { id: nextId('payer'), tenantId, code: command.code, name: command.name, type: command.type || 'Other', status: UI12_STATUS.ACTIVE }; state.payers = [...state.payers, item]; audit('Payer Created', 'Payer', item.id, command.actor); emit(); return item.id; }
export function updatePayer(access, id, command = {}) { const item = state.payers.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.PAYER_MANAGE, item) || (command.code && duplicate(state.payers, 'code', command.code, id))) return false; state.payers = state.payers.map(value => value.id === id ? { ...value, ...command } : value); audit('Payer Updated', 'Payer', id, command.actor); emit(); return true; }
export function deactivatePayer(access, id, command = {}) { const item = state.payers.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.PAYER_MANAGE, item) || !command.reason) return false; state.payers = state.payers.map(value => value.id === id ? { ...value, status: UI12_STATUS.INACTIVE } : value); audit('Payer Deactivated', 'Payer', id, command.actor, command.reason); emit(); return true; }
export function reactivatePayer(access, id, command = {}) { const item = state.payers.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.PAYER_MANAGE, item) || !command.reason) return false; state.payers = state.payers.map(value => value.id === id ? { ...value, status: UI12_STATUS.ACTIVE } : value); audit('Payer Reactivated', 'Payer', id, command.actor, command.reason); emit(); return true; }
export function createTariff(access, command = {}) { if (!authorized(access, PERMISSIONS.TARIFF_MANAGE, command) || !command.name || !command.payerId || !command.effectiveFrom || (command.effectiveTo && command.effectiveTo < command.effectiveFrom)) return null; const item = { id: nextId('tariff'), tenantId, locationId: command.locationId || locationId, name: command.name, payerId: command.payerId, effectiveFrom: command.effectiveFrom, effectiveTo: command.effectiveTo || null, status: UI12_STATUS.DRAFT, lines: [] }; state.tariffs = [...state.tariffs, item]; audit('Tariff Created', 'Tariff', item.id, command.actor); emit(); return item.id; }
export function addTariffLine(access, tariffId, command = {}) { const tariff = state.tariffs.find(item => item.id === tariffId); const service = state.services.find(item => item.id === command.serviceId); if (!tariff || !service || !authorized(access, PERMISSIONS.TARIFF_MANAGE, tariff) || Number(command.rate) < 0 || !command.unit) return null; const line = { id: nextId('tariff-line'), serviceId: service.id, rate: Number(command.rate), currency: command.currency || 'INR', unit: command.unit, status: UI12_STATUS.ACTIVE }; state.tariffs = state.tariffs.map(item => item.id === tariffId ? { ...item, lines: [...item.lines, line] } : item); audit('Tariff Line Added', 'Tariff', tariffId, command.actor); emit(); return line.id; }
export function updateTariff(access, id, command = {}) { const item = state.tariffs.find(value => value.id === id); if (!item || ![UI12_STATUS.DRAFT, UI12_STATUS.ACTIVE].includes(item.status) || !authorized(access, PERMISSIONS.TARIFF_MANAGE, item) || (command.effectiveTo && command.effectiveTo < (command.effectiveFrom || item.effectiveFrom))) return false; state.tariffs = state.tariffs.map(value => value.id === id ? { ...value, ...command, lines: command.rate !== undefined && value.lines.length ? value.lines.map((line, index) => index === 0 ? { ...line, rate: Number(command.rate) } : line) : value.lines } : value); audit('Tariff Updated', 'Tariff', id, command.actor); emit(); return true; }
export function updateTariffLine(access, tariffId, lineId, command = {}) { const item = state.tariffs.find(value => value.id === tariffId); if (!item || item.status !== UI12_STATUS.DRAFT || !authorized(access, PERMISSIONS.TARIFF_MANAGE, item) || Number(command.rate) < 0) return false; state.tariffs = state.tariffs.map(value => value.id === tariffId ? { ...value, lines: value.lines.map(line => line.id === lineId ? { ...line, ...command, rate: Number(command.rate) } : line) } : value); audit('Tariff Line Updated', 'Tariff', tariffId, command.actor); emit(); return true; }
export function activateTariff(access, id, command = {}) { const item = state.tariffs.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.TARIFF_MANAGE, item) || !item.lines.length) return false; state.tariffs = state.tariffs.map(value => value.id === id ? { ...value, status: UI12_STATUS.ACTIVE } : value); audit('Tariff Activated', 'Tariff', id, command.actor); emit(); return true; }
export function supersedeTariff(access, id, command = {}) { const item = state.tariffs.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.TARIFF_MANAGE, item) || !command.reason) return false; state.tariffs = state.tariffs.map(value => value.id === id ? { ...value, status: UI12_STATUS.SUPERSEDED, effectiveTo: command.effectiveTo || now } : value); audit('Tariff Superseded', 'Tariff', id, command.actor, command.reason); emit(); return true; }
export function createInventoryItem(access, command = {}) { if (!authorized(access, PERMISSIONS.INVENTORY_ITEM_MANAGE, command) || !command.code || !command.name || duplicate(state.items, 'code', command.code)) return null; const item = { id: nextId('item'), tenantId, code: command.code, name: command.name, category: command.category || 'General', unitOfMeasure: command.unitOfMeasure || 'each', reorderLevel: Number(command.reorderLevel || 0), batchTrackingRequired: Boolean(command.batchTrackingRequired), expiryTrackingRequired: Boolean(command.expiryTrackingRequired), status: UI12_STATUS.ACTIVE }; state.items = [...state.items, item]; registerConfiguredItem(item); audit('Inventory Item Created', 'InventoryItem', item.id, command.actor); emit(); return item.id; }
export function updateInventoryItem(access, id, command = {}) { const item = state.items.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.INVENTORY_ITEM_MANAGE, item) || (command.code && duplicate(state.items, 'code', command.code, id))) return false; state.items = state.items.map(value => value.id === id ? { ...value, ...command } : value); registerConfiguredItem({ ...item, ...command }); audit('Inventory Item Updated', 'InventoryItem', id, command.actor); emit(); return true; }
export function deactivateInventoryItem(access, id, command = {}) { const item = state.items.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.INVENTORY_ITEM_MANAGE, item) || !command.reason) return false; state.items = state.items.map(value => value.id === id ? { ...value, status: UI12_STATUS.INACTIVE } : value); audit('Inventory Item Deactivated', 'InventoryItem', id, command.actor, command.reason); emit(); return true; }
export function reactivateInventoryItem(access, id, command = {}) { const item = state.items.find(value => value.id === id); if (!item || !authorized(access, PERMISSIONS.INVENTORY_ITEM_MANAGE, item) || !command.reason) return false; state.items = state.items.map(value => value.id === id ? { ...value, status: UI12_STATUS.ACTIVE } : value); registerConfiguredItem({ ...item, status: UI12_STATUS.ACTIVE }); audit('Inventory Item Reactivated', 'InventoryItem', id, command.actor, command.reason); emit(); return true; }
export function resolveTariff(serviceId, payerId, date = '20 Sep 2026') { return state.tariffs.find(tariff => tariff.payerId === payerId && tariff.status === UI12_STATUS.ACTIVE && tariff.effectiveFrom <= date && (!tariff.effectiveTo || tariff.effectiveTo >= date))?.lines.find(line => line.serviceId === serviceId) || null; }
export function resetUi12Store() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); sequence = 0; emit(); }
