import { useSyncExternalStore } from 'react';
import { addGlobalTask } from './ui4Store.js';

const clientId = 'client-1001';
const assessmentDefinitions = [{ id: 'std-wellbeing', name: 'Recovery Wellbeing Check', category: 'Recovery progress', version: 1, status: 'Active', programs: ['Residential recovery', 'Outpatient therapy'], scoringType: 'Sum score', questions: [{ id: 'q1', text: 'I can manage a difficult moment with a helpful strategy.', required: true, options: [['0', 'Not at all'], ['1', 'Sometimes'], ['2', 'Usually'], ['3', 'Almost always']] }, { id: 'q2', text: 'I feel connected to the people supporting my recovery.', required: true, options: [['0', 'Not at all'], ['1', 'A little'], ['2', 'Mostly'], ['3', 'Very much']] }, { id: 'q3', text: 'I have a clear next step for my recovery plan.', required: true, options: [['0', 'Not at all'], ['1', 'A little'], ['2', 'Mostly'], ['3', 'Very clear']] }], bands: [{ min: 0, max: 2, label: 'Needs attention' }, { min: 3, max: 6, label: 'Developing' }, { min: 7, max: 9, label: 'Established' }] }];
const initialState = { sessions: [{ id: 'session-1001', clientId, type: 'Individual Therapy', therapist: 'Nisha Verma', date: 'Today · 11:00', appointmentDate: '20 Sep 2026 · 11:00', program: 'Residential recovery', location: 'Residential Unit A · Room 2', status: 'Scheduled', documentationStatus: 'Not started', focus: '', presentation: '', topics: '', interventions: '', response: '', risk: '', plan: '', selectedGoals: ['goal-1001'], progress: [], actions: [], signer: null, signedAt: null, version: 1, amendments: [], sensitive: true }], groups: [{ id: 'group-1001', clientId, type: 'Group Therapy', facilitator: 'Nisha Verma', date: 'Tomorrow · 15:00', program: 'Residential recovery', location: 'Therapy Room 1', topic: 'Coping strategies in daily routines', status: 'Scheduled', participants: [{ id: clientId, name: 'Aarav Mehta', attendance: 'Present', engagement: 'Active', note: '', confidential: true }, { id: 'client-1002', name: 'Leah Wilson', attendance: 'Late', engagement: 'Moderate', note: 'Shared a personal reflection.', confidential: true }] }], family: [{ id: 'family-1001', clientId, clientName: 'Aarav Mehta', participants: [{ name: 'Neha Mehta', relationship: 'Partner', consent: 'Authorized for this session' }], therapist: 'Nisha Verma', date: '23 Sep 2026 · 16:00', focus: '', discussion: '', actions: '', status: 'Scheduled' }], assignments: [{ id: 'assignment-1001', clientId, definitionId: 'std-wellbeing', assignedBy: 'Dr. Meera Shah', respondent: 'Nisha Verma', due: 'Today · 17:00', reason: 'Treatment plan review', status: 'Assigned', responses: {}, score: null, interpretation: null, completedAt: null, finalizedAt: null }], tasks: [], events: [{ id: 'event-1001', clientId, type: 'Session Scheduled', title: 'Individual therapy scheduled', date: 'Today · 11:00', sessionId: 'session-1001' }], revision: 0 };
let state = structuredClone(initialState); const listeners = new Set(); const emit = () => { state = { ...state, revision: state.revision + 1 }; listeners.forEach(listener => listener()); }; const nextId = prefix => `${prefix}-${Date.now().toString(36)}`;
export function getUi5State() { return state; }
export function useUi5Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi5State, getUi5State); }
export const standardizedAssessmentDefinitionService = { source: 'MOCK', list: () => assessmentDefinitions, get: id => assessmentDefinitions.find(item => item.id === id) };
export const therapySessionService = { source: 'MOCK', list: () => state.sessions, get: id => state.sessions.find(item => item.id === id) };
export const TherapyDocumentationService = { source: 'MOCK' }; export const GroupSessionService = { source: 'MOCK' }; export const FamilySessionService = { source: 'MOCK' }; export const StandardizedAssessmentAssignmentService = { source: 'MOCK' }; export const StandardizedAssessmentResponseService = { source: 'MOCK' }; export const AssessmentScoringService = { source: 'MOCK' }; export const TherapyTimelineService = { source: 'MOCK' };
function patchSession(id, patch) { state.sessions = state.sessions.map(item => item.id === id ? { ...item, ...patch } : item); emit(); }
export function startSession(id) { const item = state.sessions.find(session => session.id === id); if (!item || item.status !== 'Scheduled') return; patchSession(id, { status: 'In Progress', documentationStatus: 'Draft' }); state.events.push({ id: nextId('event'), clientId: item.clientId, type: 'Session Started', title: 'Individual therapy started', date: 'Just now', sessionId: id }); emit(); }
export function saveSession(id, patch) { patchSession(id, { ...patch, documentationStatus: 'Draft' }); }
export function addGoalProgress(id, progress) { const session = state.sessions.find(item => item.id === id); patchSession(id, { progress: [...(session?.progress || []), { ...progress, id: nextId('progress') }] }); }
export function addSessionAction(id, action) { const item = state.sessions.find(session => session.id === id); const task = { id: nextId('task'), title: action.title, owner: action.owner, due: action.due, source: 'Therapy session', sourceModule: 'therapy', sourceRecordType: 'TherapySession', sourceRecordId: id, clientId: item?.clientId, location: item?.location?.split(' · ')[0] || 'Residential Unit A', permissions: ['therapy.view'], module: 'clinical', destinationRoute: `/therapy/sessions/${id}`, status: 'Due', sensitivity: 'clinical', context: id }; state.tasks = [...state.tasks, task]; addGlobalTask(task); patchSession(id, { actions: [...(item?.actions || []), action] }); }
export function reviewSession(id) { patchSession(id, { status: 'Awaiting Signature', documentationStatus: 'Awaiting Signature' }); }
export function signSession(id) { const item = state.sessions.find(session => session.id === id); if (!item) return; patchSession(id, { status: 'Signed', documentationStatus: 'Signed', signer: 'Dr. Meera Shah', signedAt: 'Just now', version: 1 }); state.events.push({ id: nextId('event'), clientId: item.clientId, type: 'Session Signed', title: 'Signed therapy note', date: 'Just now', sessionId: id }); emit(); }
export function amendSession(id, reason, content) { const item = state.sessions.find(session => session.id === id); patchSession(id, { amendments: [...(item?.amendments || []), { id: nextId('amend'), reason, content, version: (item?.version || 1) + 1, signedBy: 'Dr. Meera Shah', signedAt: 'Just now' }] }); }
export function updateGroup(id, patch) { state.groups = state.groups.map(item => item.id === id ? { ...item, ...patch } : item); emit(); }
export function updateFamily(id, patch) { state.family = state.family.map(item => item.id === id ? { ...item, ...patch } : item); emit(); }
export function assignAssessment(client, definitionId) { state.assignments = [...state.assignments, { id: nextId('assignment'), clientId: client, definitionId, assignedBy: 'Dr. Meera Shah', respondent: 'Nisha Verma', due: '30 Sep 2026', reason: 'Routine score review', status: 'Assigned', responses: {}, score: null, interpretation: null }]; emit(); }
export function saveAssessment(id, responses) { state.assignments = state.assignments.map(item => item.id === id ? { ...item, responses, status: 'In Progress' } : item); emit(); }
export function scoreAssessment(id) { const item = state.assignments.find(assignment => assignment.id === id); const definition = standardizedAssessmentDefinitionService.get(item.definitionId); const score = definition.questions.reduce((sum, question) => sum + Number(item.responses[question.id] ?? 0), 0); const band = definition.bands.find(candidate => score >= candidate.min && score <= candidate.max); state.assignments = state.assignments.map(candidate => candidate.id === id ? { ...candidate, score, interpretation: band.label, status: 'Completed', completedAt: 'Just now' } : candidate); emit(); }
export function finalizeAssessment(id) { state.assignments = state.assignments.map(item => item.id === id ? { ...item, status: 'Finalized', finalizedAt: 'Just now' } : item); emit(); }
export function resetUi5Store() { state = structuredClone(initialState); emit(); }