import { useSyncExternalStore } from 'react';
import { updateNotificationStatus, updateTaskStatus } from './crossCuttingStore.js';
import { addNotification, addTask } from './crossCuttingStore.js';

const mainClient = { id: 'client-1001', clientId: 'client-1001', name: 'Aarav Mehta', mrn: 'MP-240018', location: 'Residential Unit A', room: 'Room 1', bed: 'A-12', admissionId: 'adm-1001', risk: 'Review on admission', allergies: 'No known allergies', leaveStatus: 'In residence' };
const initialState = {
  shifts: [{ id: 'shift-1001', location: 'Residential Unit A', unit: 'Residential Unit A', type: 'Day shift', start: '20 Sep 2026 · 07:00', end: '20 Sep 2026 · 19:00', status: 'Active', assignedStaff: ['Nisha Verma'], residents: ['client-1001', 'client-1002'], handoverId: 'handover-1001' }],
  residents: [mainClient, { id: 'client-1002', clientId: 'client-1002', name: 'Leah Wilson', mrn: 'MP-239881', location: 'Residential Unit A', room: 'Room 2', bed: 'A-14', admissionId: 'adm-1002', risk: 'No immediate risk', allergies: 'Penicillin allergy recorded', leaveStatus: 'In residence' }, { id: 'client-1003', clientId: 'client-1003', name: 'Sofia Khan', mrn: 'MP-239999', location: 'Centre B', room: 'Room 9', bed: 'C-01', admissionId: 'adm-1003', risk: 'No immediate risk', allergies: 'No known allergies', leaveStatus: 'In residence' }, { id: 'client-2001', clientId: 'client-2001', name: 'Tara Singh', mrn: 'T2-1001', location: 'Tenant T2 Centre', room: 'Room 1', bed: 'T2-01', admissionId: 't2-adm-1001', risk: 'No immediate risk', allergies: 'No known allergies', leaveStatus: 'In residence' }],
  observations: [{ id: 'obs-1001', clientId: 'client-1001', type: 'Wellbeing check', value: 'Engaged and comfortable', unit: null, observedAt: '20 Sep 2026 · 08:15', recordedAt: '20 Sep 2026 · 08:20', recordedBy: 'Nisha Verma', note: 'Morning check completed.', status: 'Finalized', corrections: [] }],
  checks: [{ id: 'check-1001', clientId: 'client-1001', category: 'General wellbeing', due: '20 Sep 2026 · 10:00', status: 'Due', note: '' }, { id: 'check-1002', clientId: 'client-1002', category: 'Hydration check', due: '20 Sep 2026 · 09:30', status: 'Completed', note: 'Hydration encouraged.' }],
  residentialNotes: [],
  medicationOrders: [{ id: 'med-1001', clientId: 'client-1001', medication: 'Sertraline', form: 'Tablet', strength: '50 mg', dose: '50 mg', route: 'Oral', frequency: 'Once daily', schedule: '08:00', startDate: '18 Sep 2026', endDate: null, indication: 'As prescribed', prn: false, status: 'Active', prescriber: 'Dr. Meera Shah', instructions: 'Administer with water.', version: 1 }, { id: 'med-1002', clientId: 'client-1001', medication: 'Paracetamol', form: 'Tablet', strength: '500 mg', dose: '500 mg', route: 'Oral', frequency: 'As required', schedule: 'PRN', startDate: '18 Sep 2026', endDate: null, indication: 'Pain or fever', prn: true, maxFrequency: 'Every 6 hours', status: 'Active', prescriber: 'Dr. Meera Shah', instructions: 'Record indication and response.', version: 1 }],
  mar: [{ id: 'mar-1001', clientId: 'client-1001', orderId: 'med-1001', scheduleEntryId: 'schedule-med-1001', scheduledTime: '20 Sep 2026 · 08:00', status: 'Due', actualTime: null, administeredBy: null, dose: '50 mg', route: 'Oral', note: '', reason: '', corrections: [] }],
  prnFollowups: [],
  incidents: [],
  handovers: [{ id: 'handover-1001', shiftId: 'shift-1001', location: 'Residential Unit A', outgoing: 'Nisha Verma', incoming: 'S. Iyer', status: 'Draft', residents: ['client-1001', 'client-1002'], summary: '', items: ['Medication due review', 'Morning wellbeing check'], sourceReferences: [{ type: 'Residential Check', id: 'check-1001', clientId: 'client-1001' }, { type: 'Task', id: 'task-nursing-check-1001', clientId: 'client-1001' }, { type: 'MAR', id: 'mar-1001', clientId: 'client-1001' }], createdBy: 'Nisha Verma', createdAt: 'Just now', finalizedBy: null, finalizedAt: null, acknowledgedBy: null, acknowledgedAt: null }],
  beds: [{ id: 'bed-1001', tenant: 'Veda Wellness', unit: 'Residential Unit A', room: 'Room 1', bed: 'A-12', status: 'Occupied', clientId: 'client-1001', occupiedSince: '18 Sep 2026 · 14:10', leaveStatus: 'In residence' }, { id: 'bed-1002', tenant: 'Veda Wellness', unit: 'Residential Unit A', room: 'Room 2', bed: 'A-14', status: 'Available', clientId: null, occupiedSince: null, leaveStatus: null }, { id: 'bed-1003', tenant: 'Veda Wellness', unit: 'Recovery Wing B', room: 'Room 3', bed: 'B-03', status: 'Available', clientId: null, occupiedSince: null, leaveStatus: null }, { id: 'bed-centre-b-1', tenant: 'Veda Wellness', unit: 'Centre B Unit', room: 'Room 9', bed: 'C-01', status: 'Occupied', clientId: 'client-1003', occupiedSince: '19 Sep 2026 · 09:00', leaveStatus: 'In residence' }, { id: 'bed-tenant2-1', tenant: 'Tenant T2', unit: 'Tenant T2 Unit', room: 'Room 1', bed: 'T2-01', status: 'Occupied', clientId: 'client-2001', occupiedSince: '19 Sep 2026 · 09:00', leaveStatus: 'In residence' }],
  occupancyHistory: [{ id: 'occupancy-1001', clientId: 'client-1001', admissionId: 'adm-1001', bedId: 'bed-1001', bed: 'A-12', room: 'Room 1', unit: 'Residential Unit A', from: '18 Sep 2026 · 14:10', to: null, status: 'Active', reason: 'Initial assignment' }],
  leaveEpisodes: [],
  events: [], revision: 0
};
const storageKey = 'medixpro-ui6-domain-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState();
state.residents = state.residents?.map(resident => resident.admissionId === undefined ? { ...resident, admissionId: resident.id === 'client-1001' ? 'adm-1001' : resident.id === 'client-1002' ? 'adm-1002' : null } : resident) || state.residents;
state.occupancyHistory = state.occupancyHistory?.map(item => item.bedId ? item : { ...item, bedId: state.beds.find(bed => bed.bed === item.bed && bed.unit === item.unit)?.id || item.bedId, admissionId: item.admissionId || state.residents.find(resident => resident.id === item.clientId)?.admissionId }) || state.occupancyHistory;
state.incidents?.filter(item => item.status === 'Closed').forEach(item => updateTaskStatus(item.id, 'Completed'));
if (state.incidents?.some(item => item.status === 'Closed')) updateNotificationStatus('notification-ui6-2', 'Completed');
let idSequence = 0;
const listeners = new Set(); const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); }; const nextId = prefix => `${prefix}-${Date.now().toString(36)}-${(++idSequence).toString(36)}`;
export function getUi6State() { return state; }
export function useUi6Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi6State, getUi6State); }
export function getMedicationSchedule(clientId) { return state.medicationOrders.filter(order => order.clientId === clientId && order.status === 'Active' && !order.prn).map(order => { const entry = state.mar.find(item => item.orderId === order.id); return { scheduleEntryId: entry?.scheduleEntryId || `schedule-${order.id}`, medicationOrderId: order.id, medication: order.medication, dose: order.dose, route: order.route, frequency: order.frequency, scheduledTime: entry?.scheduledTime || `${order.schedule} · Next`, orderStatus: order.status, administrationStatus: entry?.status || 'Scheduled', marId: entry?.id || null }; }); }
export function recordMedicationTimeline(clientId, title, recordId) { const existing = state.events.some(event => event.recordId === recordId); state.events = existing ? state.events.map(event => event.recordId === recordId ? { ...event, clientId, type: 'Medication Administered', title } : event) : [...state.events, { id: nextId('event'), clientId, type: 'Medication Administered', title, date: 'Just now', recordId }]; emit(); }
export const NursingShiftService = { source: 'MOCK' }; export const NursingObservationService = { source: 'MOCK' }; export const MedicationOrderService = { source: 'MOCK' }; export const MedicationScheduleService = { source: 'MOCK' }; export const MarService = { source: 'MOCK' }; export const PrnAdministrationService = { source: 'MOCK' }; export const ResidentialCareService = { source: 'MOCK' }; export const IncidentService = { source: 'MOCK' }; export const HandoverService = { source: 'MOCK' }; export const FacilityService = { source: 'MOCK' }; export const BedOccupancyService = { source: 'MOCK' }; export const LeaveService = { source: 'MOCK' };
function addEvent(clientId, type, title, recordId) { state.events = [...state.events, { id: nextId('event'), clientId, type, title, date: 'Just now', recordId }]; }
export function recordObservation(clientId, observation) { const item = { id: nextId('obs'), clientId, ...observation, observedAt: 'Just now', recordedAt: 'Just now', recordedBy: 'Nisha Verma', status: 'Finalized', corrections: [] }; state.observations = [...state.observations, item]; addEvent(clientId, 'Observation Recorded', `${observation.type}: ${observation.value}`, item.id); emit(); }
export function correctObservation(id, reason, value) { state.observations = state.observations.map(item => item.id === id ? { ...item, corrections: [...item.corrections, { id: nextId('correction'), reason, value, correctedBy: 'Nisha Verma', correctedAt: 'Just now' }] } : item); emit(); }
export function completeCheck(id, note) { state.checks = state.checks.map(item => item.id === id ? { ...item, status: 'Completed', note, completedBy: 'Nisha Verma', completedAt: 'Just now' } : item); const check = state.checks.find(item => item.id === id); updateTaskStatus(id, 'Completed'); addEvent(check.clientId, 'Residential Check Completed', check.category, id); emit(); }
export function addResidentialNote(clientId, note) { const existing = (state.residentialNotes || []).find(item => item.clientId === clientId && item.category === note.category && item.observation === note.observation); if (existing) return existing.id; const item = { id: nextId('res-note'), clientId, ...note, recordedBy: 'Nisha Verma', recordedAt: 'Just now', status: 'Finalized' }; state.residentialNotes = [...(state.residentialNotes || []), item]; state.events = [...state.events, { id: nextId('event'), clientId, type: 'Residential Note', title: note.category, date: 'Just now', recordId: item.id }]; emit(); return item.id; }
export function addMedicationOrder(order) { const item = { id: nextId('med'), ...order, status: 'Draft', prescriber: 'Dr. Meera Shah', version: 1 }; state.medicationOrders = [...state.medicationOrders, item]; emit(); }
export function activateMedicationOrder(id) { state.medicationOrders = state.medicationOrders.map(item => item.id === id ? { ...item, status: 'Active' } : item); emit(); }
export function discontinueMedicationOrder(id, reason) { state.medicationOrders = state.medicationOrders.map(item => item.id === id ? { ...item, status: 'Discontinued', discontinuedAt: 'Just now', discontinueReason: reason, version: item.version + 1 } : item); emit(); }
export function recordMar(id, outcome, details = {}) { const entry = state.mar.find(item => item.id === id); if (!entry || (['Refused', 'Withheld', 'Omitted', 'Client Away'].includes(outcome) && !details.reason)) return false; const patch = { status: outcome, ...details, actualTime: outcome === 'Administered' ? 'Just now' : null, administeredBy: outcome === 'Administered' ? 'Nisha Verma' : null }; state.mar = state.mar.map(item => item.id === id ? { ...item, ...patch } : item); const order = state.medicationOrders.find(item => item.id === entry.orderId); addEvent(entry.clientId, `Medication ${outcome}`, order?.prn ? `PRN ${order.medication} ${order.dose} - ${entry.reason}` : 'MAR entry finalized', id); if (order?.prn && outcome === 'Administered' && !state.prnFollowups.some(item => item.marId === id)) { const followup = { id: nextId('prn-followup'), marId: id, status: 'Due', response: null, note: '', due: 'Within 60 minutes' }; state.prnFollowups = [...state.prnFollowups, followup]; addTask({ id: nextId('task'), title: 'PRN effectiveness follow-up', owner: 'Nisha Verma', due: 'Within 60 minutes', status: 'Due', sourceModule: 'medication', sourceRecordType: 'PRNFollowup', sourceRecordId: followup.id, clientId: entry.clientId, location: 'Residential Unit A', permissions: ['prn.effectiveness.record'], module: 'medication', destinationRoute: `/clients/${entry.clientId}/prn-followup/${followup.id}`, sensitivity: 'clinical' }); addNotification({ id: nextId('notification'), title: 'PRN follow-up due', detail: `${order.medication} effectiveness review`, category: 'medication', sourceModule: 'medication', sourceRecordType: 'PRNFollowup', sourceRecordId: followup.id, location: 'Residential Unit A', permissions: ['prn.effectiveness.record'], module: 'medication', destinationRoute: `/clients/${entry.clientId}/prn-followup/${followup.id}`, sensitivity: 'clinical' }); } if (outcome !== 'Administered') addTask({ id: nextId('task'), title: `Medication exception: ${outcome}`, owner: 'Nisha Verma', due: 'Today', status: 'Due', sourceModule: 'medication', sourceRecordType: 'MAR', sourceRecordId: id, clientId: entry.clientId, location: 'Residential Unit A', permissions: ['mar.view'], module: 'medication', destinationRoute: `/clients/${entry.clientId}/mar`, sensitivity: 'clinical' }); emit(); return true; }
export function createPrnAdministration(orderId, reason) { const order = state.medicationOrders.find(item => item.id === orderId); if (!order || !order.prn || order.status !== 'Active' || !reason) return null; const item = { id: nextId('mar-prn'), clientId: order.clientId, orderId, scheduledTime: 'Now · PRN', status: 'Due', actualTime: null, administeredBy: null, dose: order.dose, route: order.route, note: '', reason }; state.mar = [...state.mar, item]; emit(); return item.id; }
export function correctMar(id, reason, patch) { if (!reason) return false; state.mar = state.mar.map(item => item.id === id ? { ...item, corrections: [...item.corrections, { id: nextId('mar-correction'), original: { status: item.status, dose: item.dose, route: item.route, actualTime: item.actualTime, administeredBy: item.administeredBy }, corrected: patch, reason, correctedBy: 'Nisha Verma', correctedAt: 'Just now' }] } : item); emit(); return true; }
export function recordPrnFollowup(marId, response, note) { const existing = state.prnFollowups.find(item => item.marId === marId && item.status === 'Due'); const item = existing ? { ...existing, response, note, recordedBy: 'Nisha Verma', recordedAt: 'Just now', status: 'Completed' } : { id: nextId('prn-followup'), marId, response, note, recordedBy: 'Nisha Verma', recordedAt: 'Just now', status: 'Completed' }; state.prnFollowups = existing ? state.prnFollowups.map(entry => entry.id === existing.id ? item : entry) : [...state.prnFollowups, item]; updateTaskStatus(item.id, 'Completed'); updateNotificationStatus(item.id, 'Completed'); addEvent(state.mar.find(entry => entry.id === marId)?.clientId, 'PRN Follow-up Completed', `${response} - ${note}`, item.id); emit(); }
export function createIncident(incident) { const item = { id: nextId('incident'), ...incident, status: 'Submitted', createdBy: 'Nisha Verma', createdAt: 'Just now' }; state.incidents = [...state.incidents, item]; addEvent(item.clientId, 'Incident Submitted', item.category, item.id); addTask({ id: nextId('task'), title: 'Review residential incident', owner: 'Centre supervisor', due: 'Today', status: 'Due', sourceModule: 'residential', sourceRecordType: 'Incident', sourceRecordId: item.id, clientId: item.clientId, location: item.location, permissions: ['incident.review'], module: 'residential', destinationRoute: `/incidents/${item.id}`, sensitivity: 'clinical' }); addNotification({ id: nextId('notification'), title: 'Residential incident requires review', detail: `${item.category} · Residential Unit A`, category: 'incident', sourceModule: 'residential', sourceRecordType: 'Incident', sourceRecordId: item.id, location: item.location, permissions: ['incident.review'], module: 'residential', destinationRoute: `/incidents/${item.id}`, sensitivity: 'clinical' }); emit(); }
export function updateIncident(id, patch) { state.incidents = state.incidents.map(item => item.id === id ? { ...item, ...patch } : item); const incident = state.incidents.find(item => item.id === id); if (patch.status === 'Closed') { updateTaskStatus(id, 'Completed'); updateNotificationStatus(id, 'Completed'); updateNotificationStatus('notification-ui6-2', 'Completed'); addEvent(incident.clientId, 'Incident Closed', incident.category, id); } emit(); }
export function reviewIncident(id, reviewNotes, status = 'Under Review') { state.incidents = state.incidents.map(item => item.id === id ? { ...item, status, reviewNotes, reviewedBy: 'Centre supervisor', reviewedAt: 'Just now' } : item); emit(); }
export function updateHandover(id, patch) { state.handovers = state.handovers.map(item => item.id === id ? { ...item, ...patch } : item); emit(); }
export function finalizeHandover(id) { state.handovers = state.handovers.map(item => item.id === id ? { ...item, status: 'Finalized', finalizedBy: 'Nisha Verma', finalizedAt: 'Just now' } : item); addEvent(state.handovers.find(item => item.id === id)?.residents?.[0], 'Shift Handover Finalized', 'Handover finalized', id); emit(); }
export function acknowledgeHandover(id) { state.handovers = state.handovers.map(item => item.id === id ? { ...item, status: 'Acknowledged', acknowledgedBy: 'S. Iyer', acknowledgedAt: 'Just now' } : item); addEvent(state.handovers.find(item => item.id === id)?.residents?.[0], 'Shift Handover Acknowledged', 'Handover acknowledged', id); emit(); }
export function assignBed(clientId, bedId) { const target = state.beds.find(bed => bed.id === bedId); const resident = state.residents.find(item => item.id === clientId); const activeOccupancy = state.beds.find(bed => bed.clientId === clientId && bed.status === 'Occupied'); if (!target || target.status !== 'Available' || !resident || activeOccupancy || resident.admissionId === null) return false; state.beds = state.beds.map(bed => bed.id === bedId ? { ...bed, status: 'Occupied', clientId, admissionId: resident.admissionId, occupiedSince: 'Just now', assignedBy: 'Centre administrator', leaveStatus: 'In residence' } : bed); state.residents = state.residents.map(item => item.id === clientId ? { ...item, room: target.room, bed: target.bed } : item); state.occupancyHistory = [...state.occupancyHistory, { id: nextId('occupancy'), clientId, admissionId: resident.admissionId, bedId, bed: target.bed, room: target.room, unit: target.unit, from: 'Just now', to: null, reason: 'Initial assignment', assignedBy: 'Centre administrator' }]; addEvent(clientId, 'Bed Assigned', `${target.room} · ${target.bed}`, bedId); emit(); return true; }
export function registerConfiguredBed(bed, options = {}) { const existing = state.beds.find(item => item.id === bed.id); if (options.checkOnly) return existing || null; if (existing) return existing.id; const room = bed.room || bed.roomNumber || 'Configured room'; const unit = bed.unit || 'Configured unit'; state.beds = [...state.beds, { id: bed.id, tenant: bed.tenantId, unit, room, bed: bed.label || bed.code, status: 'Available', clientId: null, occupiedSince: null, leaveStatus: null, configurationStatus: bed.status }]; emit(); return bed.id; }
export function transferBed(clientId, targetId, reason) { const target = state.beds.find(bed => bed.id === targetId); const current = state.beds.find(bed => bed.clientId === clientId && bed.status === 'Occupied'); const resident = state.residents.find(item => item.id === clientId); const activeHistory = state.occupancyHistory.find(item => item.clientId === clientId && !item.to); if (!target || target.status !== 'Available' || !current || !resident?.admissionId || !activeHistory || target.id === current.id) return false; const transferAt = 'Just now'; const destinationOccupancyId = nextId('occupancy'); state.beds = state.beds.map(bed => bed.id === current.id ? { ...bed, status: 'Available', clientId: null, occupiedSince: null, leaveStatus: null } : bed.id === targetId ? { ...bed, status: 'Occupied', clientId, admissionId: resident.admissionId, occupiedSince: transferAt, assignedBy: 'Centre administrator', leaveStatus: 'In residence' } : bed); state.residents = state.residents.map(item => item.id === clientId ? { ...item, room: target.room, bed: target.bed } : item); state.occupancyHistory = [...state.occupancyHistory.map(item => item.id === activeHistory.id ? { ...item, to: transferAt, status: 'Transferred', transferReason: reason, transferredBy: 'Centre administrator' } : item), { id: destinationOccupancyId, clientId, admissionId: resident.admissionId, bedId: targetId, bed: target.bed, room: target.room, unit: target.unit, from: transferAt, to: null, status: 'Active', reason: `Internal transfer: ${reason}`, transferredFrom: activeHistory.id, transferredBy: 'Centre administrator' }]; addEvent(clientId, 'Bed Transferred', `${current.room} / ${current.bed} → ${target.room} / ${target.bed}`, destinationOccupancyId); emit(); return destinationOccupancyId; }
export function startLeave(clientId, expectedReturn, note) { const resident = state.residents.find(item => item.id === clientId); const bed = state.beds.find(item => item.clientId === clientId && item.status === 'Occupied'); if (!resident || !resident.admissionId || !bed || resident.leaveStatus === 'On leave' || !expectedReturn || !note) return false; const episode = { id: nextId('leave'), clientId, admissionId: resident.admissionId, occupancyId: state.occupancyHistory.find(item => item.clientId === clientId && !item.to)?.id, bedId: bed.id, bed: bed.bed, room: bed.room, startedAt: 'Just now', expectedReturn, reason: note, startedBy: 'Nisha Verma', returnedAt: null, returnedBy: null, status: 'Active' }; state.leaveEpisodes = [...(state.leaveEpisodes || []), episode]; state.residents = state.residents.map(item => item.id === clientId ? { ...item, leaveStatus: 'On leave', expectedReturn, leaveNote: note } : item); state.beds = state.beds.map(item => item.id === bed.id ? { ...item, leaveStatus: 'On leave', holdForClientId: clientId } : item); addEvent(clientId, 'Leave Started', `Bed held ${bed.room} · ${bed.bed}`, episode.id); emit(); return episode.id; }
export function returnFromLeave(clientId) { const episode = (state.leaveEpisodes || []).find(item => item.clientId === clientId && item.status === 'Active'); const bed = state.beds.find(item => item.id === episode?.bedId); if (!episode || !bed || bed.holdForClientId !== clientId) return false; state.leaveEpisodes = state.leaveEpisodes.map(item => item.id === episode.id ? { ...item, status: 'Completed', returnedAt: 'Just now', returnedBy: 'Nisha Verma' } : item); state.residents = state.residents.map(item => item.id === clientId ? { ...item, leaveStatus: 'In residence', expectedReturn: null } : item); state.beds = state.beds.map(item => item.id === bed.id ? { ...item, leaveStatus: 'In residence', holdForClientId: null } : item); addEvent(clientId, 'Returned From Leave', `Bed restored ${bed.room} · ${bed.bed}`, episode.id); emit(); return true; }
export function releaseBedForDischarge(clientId) { const bed = state.beds.find(item => item.clientId === clientId); if (!bed) return false; state.beds = state.beds.map(item => item.id === bed.id ? { ...item, status: 'Available', clientId: null, occupiedSince: null, leaveStatus: null } : item); state.occupancyHistory = state.occupancyHistory.map(item => item.clientId === clientId && !item.to ? { ...item, to: 'Just now', reason: 'Discharge-side release' } : item); addEvent(clientId, 'Bed Released', `${bed.room} · ${bed.bed}`, bed.id); emit(); return true; }
export function resetUi6Store() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); emit(); }
