import { useSyncExternalStore } from 'react';
import { addNotification, addTask } from './crossCuttingStore.js';
import { closeCanonicalAdmission } from './ui3Store.js';
import { getUi6State, releaseBedForDischarge } from './ui6Store.js';

export const UI8_STATUS = Object.freeze({ DRAFT: 'Draft', ACTIVE: 'Active', FINALIZED: 'Finalized', SUPERSEDED: 'Superseded', COMPLETED: 'Completed', CANCELLED: 'Cancelled', SCHEDULED: 'Scheduled', CONFIRMED: 'Confirmed', READY: 'Ready', IN_PROGRESS: 'InProgress', NO_SHOW: 'NoShow', NOT_STARTED: 'NotStarted', IN_PROGRESS_ITEM: 'InProgress', NOT_APPLICABLE: 'NotApplicable', BLOCKED: 'Blocked', OPEN: 'Open', RESCHEDULED: 'Rescheduled', ESCALATED: 'Escalated' });
const tenantId = 'Veda Wellness';
const locationId = 'Greater Noida Centre';
const clientId = 'client-1001';
const admissionId = 'adm-1001';
const now = '20 Sep 2026 · 09:00';
const initialState = {
  nutritionAssessments: [{ id: 'nutrition-assessment-1001', tenantId, locationId, clientId, admissionId, status: UI8_STATUS.FINALIZED, nutritionStatus: 'At risk', dietaryPattern: 'Regular meals with reduced appetite', restrictions: 'Reference canonical allergy record', swallowing: 'No concern recorded', risks: 'Reduced appetite', goals: 'Maintain adequate intake during recovery', recommendations: 'Monitor intake and review weekly.', createdAt: '18 Sep 2026 · 11:00', createdBy: 'Dietitian', finalizedAt: '18 Sep 2026 · 12:00', finalizedBy: 'Dietitian', version: 1 }],
  nutritionPlans: [{ id: 'nutrition-plan-1001', assessmentId: 'nutrition-assessment-1001', tenantId, locationId, clientId, admissionId, status: UI8_STATUS.ACTIVE, goals: ['Maintain adequate intake'], dietaryRequirements: 'Regular meals; encourage fluids', interventions: 'Weekly nutrition review', responsibleProfessional: 'Dietitian', nextReview: '27 Sep 2026', createdAt: '18 Sep 2026 · 12:15', createdBy: 'Dietitian', activatedAt: '18 Sep 2026 · 12:30', activatedBy: 'Dietitian', version: 1 }],
  nutritionFollowUps: [{ id: 'nutrition-followup-1001', planId: 'nutrition-plan-1001', tenantId, locationId, clientId, admissionId, status: UI8_STATUS.SCHEDULED, dueDate: '27 Sep 2026', progress: '', adherence: '', recommendation: '' }],
  caregivers: [{ id: 'caregiver-1001', tenantId, locationId, clientId, name: 'Neha Mehta', relationship: 'Partner', contact: '+91 98765 44099', primary: true, emergency: true, involvement: 'Active', authorizationStatus: 'Authorized recipient', consentReference: 'consent-ui3-1001', restrictions: 'Care coordination and discharge planning only', communicationPreference: 'Phone' }],
  familySessions: [{ id: 'family-session-1001', tenantId, locationId, clientId, admissionId, caregiverId: 'caregiver-1001', type: 'Care Conference', status: UI8_STATUS.SCHEDULED, scheduledAt: '24 Sep 2026 · 16:00', purpose: 'Discharge preparation', participants: ['Neha Mehta'], outcome: '', followUp: '', createdAt: '19 Sep 2026 · 10:00', createdBy: 'Arjun Rao' }],
  caregiverEducation: [],
  telehealthAppointments: [{ id: 'telehealth-1001', tenantId, locationId, clientId, admissionId, service: 'Clinical follow-up', clinician: 'Dr. Meera Shah', scheduledAt: '26 Sep 2026 · 15:00', durationMinutes: 30, participants: ['Aarav Mehta'], readiness: 'Confirm private setting', status: UI8_STATUS.SCHEDULED, createdAt: '19 Sep 2026 · 11:00', createdBy: 'Arjun Rao', version: 1 }],
  dischargePlans: [{ id: 'discharge-plan-1001', tenantId, locationId, clientId, admissionId, status: 'InPlanning', targetDate: '30 Sep 2026', destination: 'Home with community support', coordinator: 'Arjun Rao', disposition: 'Completed residential episode', checklist: [{ id: 'clinical', label: 'Clinical readiness', required: true, status: 'Completed', owner: 'Dr. Meera Shah', sourceReference: 'assess-1001' }, { id: 'medical', label: 'Medical review', required: true, status: 'Completed', owner: 'Dr. Meera Shah' }, { id: 'medication', label: 'Medication reconciliation reference', required: true, status: 'Completed', owner: 'Dr. Meera Shah', sourceReference: 'med-1001' }, { id: 'therapy', label: 'Therapy summary', required: true, status: 'Completed', owner: 'Nisha Verma', sourceReference: 'session-1001' }, { id: 'nutrition', label: 'Nutrition considerations', required: true, status: 'Completed', owner: 'Dietitian', sourceReference: 'nutrition-plan-1001' }, { id: 'family', label: 'Family / caregiver preparation', required: true, status: 'InProgress', owner: 'Arjun Rao' }, { id: 'follow-up', label: 'Follow-up arrangements', required: true, status: 'Completed', owner: 'Arjun Rao' }, { id: 'aftercare', label: 'Aftercare plan', required: true, status: 'Completed', owner: 'Arjun Rao' }, { id: 'destination', label: 'Destination confirmed', required: true, status: 'Completed', owner: 'Arjun Rao' }, { id: 'documents', label: 'Required documents', required: true, status: 'Completed', owner: 'Intake team' }, { id: 'financial', label: 'Financial clearance reference', required: false, status: UI8_STATUS.NOT_APPLICABLE, owner: 'Billing' }, { id: 'approval', label: 'Final authorization', required: true, status: 'NotStarted', owner: 'Medical director' }] }],
  dischargeSummaries: [],
  aftercarePlans: [{ id: 'aftercare-plan-1001', tenantId, locationId, clientId, admissionId, dischargePlanId: 'discharge-plan-1001', status: UI8_STATUS.DRAFT, services: ['Community recovery support'], responsiblePerson: 'Arjun Rao', supportActions: 'Continue recovery routines and community follow-up', safetyPlan: 'Escalate significant deterioration through existing clinical/incident pathways', createdAt: now, createdBy: 'Arjun Rao' }],
  aftercareFollowUps: [{ id: 'aftercare-followup-1001', tenantId, locationId, clientId, admissionId, aftercarePlanId: 'aftercare-plan-1001', type: 'Care coordination call', scheduledAt: '07 Oct 2026 · 10:00', status: UI8_STATUS.SCHEDULED, outcome: '', nextAction: '' }],
  events: [{ id: 'nutrition-assessment:nutrition-assessment-1001:finalized', clientId, admissionId, type: 'Nutrition Assessment Finalized', title: 'Nutrition assessment finalized', date: '18 Sep 2026 · 12:00', recordId: 'nutrition-assessment-1001' }],
  revision: 0
};
const storageKey = 'medixpro-ui8-domain-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState();
let sequence = 0;
const listeners = new Set();
const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
const nextId = prefix => { let id; do { id = `${prefix}-${++sequence}`; } while (Object.values(state).some(value => Array.isArray(value) && value.some(item => item?.id === id))); return id; };
const scoped = (access, item) => (!item.tenantId || item.tenantId === access?.tenant || access?.tenant === 'MedixPro360 Platform') && (!item.locationId || ['All regions', 'All centres', 'All permitted centres'].includes(access?.location) || item.locationId === access?.location || access?.location === 'Greater Noida Centre');
const event = (id, type, title, recordId, client = clientId, admission = admissionId) => ({ id, clientId: client, admissionId: admission, type, title, date: now, recordId });
function mutate(collection, id, patch) { state[collection] = state[collection].map(item => item.id === id ? { ...item, ...patch } : item); emit(); }
export function getUi8State() { return state; }
export function useUi8Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi8State, getUi8State); }
export function getUi8VisibleRecords(access) { return Object.fromEntries(Object.entries(state).filter(([, value]) => Array.isArray(value)).map(([key, value]) => [key, value.filter(item => scoped(access, item))])); }
export function finalizeNutritionAssessment(id, command = {}) { const item = state.nutritionAssessments.find(value => value.id === id); if (!item || item.status === UI8_STATUS.FINALIZED || !item.nutritionStatus || !item.goals) return false; state.nutritionAssessments = state.nutritionAssessments.map(value => value.id === id ? { ...value, status: UI8_STATUS.FINALIZED, finalizedAt: now, finalizedBy: command.actor || 'Dietitian' } : value); state.events = [...state.events, event(`nutrition-assessment:${id}:finalized`, 'Nutrition Assessment Finalized', 'Nutrition assessment finalized', id, item.clientId, item.admissionId)]; emit(); return true; }
export function createNutritionPlan(command) { if (!command?.assessmentId || !command?.goals?.length) return null; const assessment = state.nutritionAssessments.find(item => item.id === command.assessmentId); if (!assessment || assessment.status !== UI8_STATUS.FINALIZED) return null; const item = { id: nextId('nutrition-plan'), assessmentId: assessment.id, tenantId, locationId, clientId: assessment.clientId, admissionId: assessment.admissionId, status: UI8_STATUS.DRAFT, goals: command.goals, dietaryRequirements: command.dietaryRequirements || '', interventions: command.interventions || '', responsibleProfessional: command.responsibleProfessional || 'Dietitian', nextReview: command.nextReview || '30 Sep 2026', createdAt: now, createdBy: command.actor || 'Dietitian', version: 1 }; state.nutritionPlans = [...state.nutritionPlans, item]; emit(); return item.id; }
export function activateNutritionPlan(id, command = {}) { const item = state.nutritionPlans.find(value => value.id === id); if (!item || item.status !== UI8_STATUS.DRAFT || !item.goals.length) return false; state.nutritionPlans = state.nutritionPlans.map(value => value.id === id ? { ...value, status: UI8_STATUS.ACTIVE, activatedAt: now, activatedBy: command.actor || 'Dietitian' } : value); state.events = [...state.events, event(`nutrition-plan:${id}:activated`, 'Nutrition Plan Activated', 'Nutrition plan activated', id, item.clientId, item.admissionId)]; emit(); return true; }
export function recordNutritionFollowUp(id, patch, command = {}) { const item = state.nutritionFollowUps.find(value => value.id === id); if (!item || item.status === UI8_STATUS.COMPLETED) return false; mutate('nutritionFollowUps', id, { ...patch, status: UI8_STATUS.COMPLETED, completedAt: now, completedBy: command.actor || 'Dietitian' }); return true; }
export function addCaregiver(command) { if (!command?.clientId || !command?.name || !command?.authorizationStatus) return null; const item = { id: nextId('caregiver'), tenantId, locationId, clientId: command.clientId, name: command.name, relationship: command.relationship || 'Caregiver', contact: command.contact || '', primary: Boolean(command.primary), emergency: Boolean(command.emergency), involvement: 'Active', authorizationStatus: command.authorizationStatus, consentReference: command.consentReference || null, restrictions: command.restrictions || 'No clinical disclosure without explicit authorization', communicationPreference: command.communicationPreference || 'Phone' }; state.caregivers = [...state.caregivers, item]; emit(); return item.id; }
export function recordFamilySession(id, patch, command = {}) { const item = state.familySessions.find(value => value.id === id); if (!item || !command?.authorizationChecked) return false; mutate('familySessions', id, { ...patch, status: UI8_STATUS.COMPLETED, completedAt: now, completedBy: command.actor || 'Care coordinator' }); return true; }
export function recordCaregiverEducation(command) { if (!command?.clientId || !command?.topic || !command?.recipient) return null; const item = { id: nextId('caregiver-education'), tenantId, locationId, clientId: command.clientId, topic: command.topic, recipient: command.recipient, providedAt: now, providedBy: command.actor || 'Care coordinator', acknowledgement: command.acknowledgement || 'Recorded', followUp: command.followUp || '' }; state.caregiverEducation = [...state.caregiverEducation, item]; emit(); return item.id; }
export function scheduleTelehealthAppointment(command) { if (!command?.clientId || !command?.scheduledAt || !command?.clinician) return null; const item = { id: nextId('telehealth'), tenantId, locationId, clientId: command.clientId, admissionId: command.admissionId || admissionId, service: command.service || 'Clinical follow-up', clinician: command.clinician, scheduledAt: command.scheduledAt, durationMinutes: command.durationMinutes || 30, participants: command.participants || ['Aarav Mehta'], readiness: command.readiness || 'Confirm private setting', status: UI8_STATUS.SCHEDULED, createdAt: now, createdBy: command.actor || 'Care coordinator', version: 1 }; state.telehealthAppointments = [...state.telehealthAppointments, item]; emit(); return item.id; }
export function startTelehealthSession(id, command = {}) { const item = state.telehealthAppointments.find(value => value.id === id); if (!item || ![UI8_STATUS.SCHEDULED, UI8_STATUS.CONFIRMED, UI8_STATUS.READY].includes(item.status)) return false; mutate('telehealthAppointments', id, { status: UI8_STATUS.IN_PROGRESS, startedAt: now, startedBy: command.actor || 'Clinician', version: item.version + 1 }); return true; }
export function completeTelehealthSession(id, patch, command = {}) { const item = state.telehealthAppointments.find(value => value.id === id); if (!item || item.status !== UI8_STATUS.IN_PROGRESS || !patch?.outcome) return false; state.telehealthAppointments = state.telehealthAppointments.map(value => value.id === id ? { ...value, ...patch, status: UI8_STATUS.COMPLETED, completedAt: now, completedBy: command.actor || 'Clinician', version: value.version + 1 } : value); state.events = [...state.events, event(`telehealth:${id}:completed`, 'Telehealth Session Completed', 'Telehealth session completed', id, item.clientId, item.admissionId)]; emit(); return true; }
export function cancelTelehealthAppointment(id, reason, command = {}) { const item = state.telehealthAppointments.find(value => value.id === id); if (!item || !reason || [UI8_STATUS.COMPLETED, UI8_STATUS.CANCELLED, UI8_STATUS.NO_SHOW].includes(item.status)) return false; mutate('telehealthAppointments', id, { status: UI8_STATUS.CANCELLED, reason, cancelledAt: now, cancelledBy: command.actor || 'Coordinator', version: item.version + 1 }); return true; }
export function markTelehealthNoShow(id, reason, command = {}) { const item = state.telehealthAppointments.find(value => value.id === id); if (!item || !reason || [UI8_STATUS.COMPLETED, UI8_STATUS.CANCELLED, UI8_STATUS.NO_SHOW].includes(item.status)) return false; mutate('telehealthAppointments', id, { status: UI8_STATUS.NO_SHOW, reason, noShowAt: now, markedBy: command.actor || 'Coordinator', version: item.version + 1 }); return true; }
export function updateDischargeReadiness(planId, itemId, patch, command = {}) { const plan = state.dischargePlans.find(value => value.id === planId); if (!plan || plan.status === UI8_STATUS.FINALIZED) return false; state.dischargePlans = state.dischargePlans.map(value => value.id === planId ? { ...value, checklist: value.checklist.map(item => item.id === itemId ? { ...item, ...patch, completedAt: patch.status === 'Completed' ? now : item.completedAt, completedBy: patch.status === 'Completed' ? command.actor || 'Coordinator' : item.completedBy } : item) } : value); emit(); return true; }
export function reviewDischargePlan(planId, command = {}) { const plan = state.dischargePlans.find(value => value.id === planId); if (!plan || plan.checklist.some(item => item.required && !['Completed', UI8_STATUS.NOT_APPLICABLE].includes(item.status))) return false; mutate('dischargePlans', planId, { status: 'ReadyForDischarge', reviewedAt: now, reviewedBy: command.actor || 'Medical director' }); return true; }
export function finalizeDischarge(command = {}) { const plan = state.dischargePlans.find(value => value.id === command.dischargePlanId); if (!plan || plan.status !== 'ReadyForDischarge' || plan.clientId !== command.clientId || plan.admissionId !== command.admissionId || !command.disposition) return false; const canonical = getUi6State(); const activeOccupancy = canonical.occupancyHistory.find(item => item.clientId === command.clientId && item.admissionId === command.admissionId && !item.to); if (!activeOccupancy) return false; state.dischargePlans = state.dischargePlans.map(value => value.id === plan.id ? { ...value, status: UI8_STATUS.FINALIZED, finalizedAt: now, finalizedBy: command.actor || 'Centre administrator', disposition: command.disposition, destination: command.destination } : value); closeCanonicalAdmission(command.clientId, command.admissionId, { disposition: command.disposition, dischargedAt: now, dischargedBy: command.actor || 'Centre administrator' }); releaseBedForDischarge(command.clientId); state.events = [...state.events, event(`discharge:${plan.id}:finalized`, 'Discharge Finalized', 'Discharge finalized', plan.id, command.clientId, command.admissionId)]; addTask({ id: `task:${plan.id}:aftercare`, title: 'Activate aftercare plan', owner: 'Care coordinator', due: 'Today', status: 'Due', sourceModule: 'discharge', sourceRecordType: 'DischargePlan', sourceRecordId: plan.id, clientId: command.clientId, tenant: tenantId, location: locationId, permissions: ['aftercare.plan.manage'], module: 'aftercare', destinationRoute: `/aftercare/plans/${plan.id}`, sensitivity: 'clinical' }); emit(); return true; }
export function activateAftercarePlan(id, command = {}) { const item = state.aftercarePlans.find(value => value.id === id); if (!item || item.status !== UI8_STATUS.DRAFT) return false; state.aftercarePlans = state.aftercarePlans.map(value => value.id === id ? { ...value, status: UI8_STATUS.ACTIVE, activatedAt: now, activatedBy: command.actor || 'Care coordinator' } : value); state.events = [...state.events, event(`aftercare:${id}:activated`, 'Aftercare Plan Activated', 'Aftercare plan activated', id, item.clientId, item.admissionId)]; emit(); return true; }
export function scheduleAftercareFollowUp(command) { if (!command?.aftercarePlanId || !command?.scheduledAt) return null; const plan = state.aftercarePlans.find(item => item.id === command.aftercarePlanId); if (!plan || ![UI8_STATUS.ACTIVE, UI8_STATUS.DRAFT].includes(plan.status)) return null; const item = { id: nextId('aftercare-followup'), tenantId, locationId, clientId: plan.clientId, admissionId: plan.admissionId, aftercarePlanId: plan.id, type: command.type || 'Care coordination call', scheduledAt: command.scheduledAt, status: UI8_STATUS.SCHEDULED, outcome: '', nextAction: '' }; state.aftercareFollowUps = [...state.aftercareFollowUps, item]; emit(); return item.id; }
export function completeAftercareFollowUp(id, patch, command = {}) { const item = state.aftercareFollowUps.find(value => value.id === id); if (!item || item.status === UI8_STATUS.COMPLETED || !patch?.outcome) return false; mutate('aftercareFollowUps', id, { ...patch, status: UI8_STATUS.COMPLETED, completedAt: now, completedBy: command.actor || 'Care coordinator' }); return true; }
export function escalateAftercareConcern(id, concern, command = {}) { const item = state.aftercareFollowUps.find(value => value.id === id); if (!item || !concern) return false; mutate('aftercareFollowUps', id, { status: UI8_STATUS.ESCALATED, concern, escalatedAt: now, escalatedBy: command.actor || 'Care coordinator' }); addNotification({ id: `notification:aftercare:${id}`, title: 'Aftercare follow-up escalated', detail: concern, category: 'aftercare', sourceModule: 'aftercare', sourceRecordType: 'AftercareFollowUp', sourceRecordId: id, tenant: tenantId, location: locationId, permissions: ['aftercare.view'], module: 'aftercare', destinationRoute: `/aftercare/follow-ups/${id}`, sensitivity: 'clinical' }); emit(); return true; }
export function resetUi8Store() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); sequence = 0; emit(); }
