import { useSyncExternalStore } from 'react';
import { addNotification, addTask } from './crossCuttingStore.js';
import { isLocationAllowed, isTenantAllowed } from './access.js';

export const UI9_STATUS = Object.freeze({ PENDING: 'Pending', READY: 'Ready', INVOICED: 'Invoiced', CANCELLED: 'Cancelled', DRAFT: 'Draft', FINALIZED: 'Finalized', ISSUED: 'Issued', OPEN: 'Open', PAID: 'Paid', VOID: 'Voided', REQUESTED: 'Requested', APPROVED: 'Approved', REJECTED: 'Rejected', PARTIAL: 'PartiallyFulfilled', FULFILLED: 'Fulfilled', ISSUED_STOCK: 'Issued', RECEIVED: 'Received', COMPLETED: 'Completed' });
const tenantId = 'Veda Wellness';
const locationId = 'Greater Noida Centre';
const clientId = 'client-1001';
const admissionId = 'adm-1001';
const now = '20 Sep 2026 · 09:00';
const initialState = {
  charges: [
    { id: 'charge-occupancy-1001', tenantId, locationId, clientId, admissionId, serviceCode: 'BED-RES', serviceName: 'Residential bed occupancy', serviceCategory: 'Facility', serviceDate: '20 Sep 2026', quantity: 1, unitPrice: 2500, grossAmount: 2500, discount: 0, tax: 0, netAmount: 2500, payerContext: 'Self Pay', sourceModule: 'facility', sourceType: 'occupancy', sourceId: 'occupancy-1001', status: UI9_STATUS.READY, createdAt: '20 Sep 2026 · 08:00', createdBy: 'Billing User' },
    { id: 'charge-therapy-1001', tenantId, locationId, clientId, admissionId, serviceCode: 'TH-IND', serviceName: 'Individual therapy session', serviceCategory: 'Therapy', serviceDate: '20 Sep 2026', quantity: 1, unitPrice: 1200, grossAmount: 1200, discount: 0, tax: 0, netAmount: 1200, payerContext: 'Self Pay', sourceModule: 'therapy', sourceType: 'session', sourceId: 'session-1001', status: UI9_STATUS.READY, createdAt: '20 Sep 2026 · 08:05', createdBy: 'Billing User' }
  ],
  invoices: [],
  payments: [],
  adjustments: [],
  items: [
    { id: 'item-med-1001', itemCode: 'MED-SER-50', name: 'Sertraline 50 mg', category: 'Medication', unitOfMeasure: 'tablet', reorderLevel: 20, batchTrackingRequired: true, expiryTrackingRequired: true, active: true },
    { id: 'item-cons-1001', itemCode: 'CONS-GLOVES', name: 'Nitrile gloves', category: 'Consumable', unitOfMeasure: 'box', reorderLevel: 10, batchTrackingRequired: false, expiryTrackingRequired: false, active: true }
  ],
  stockBalances: [
    { id: 'stock-x-med', tenantId, locationId: 'Ward X', itemId: 'item-med-1001', lotId: 'lot-ser-01', batch: 'SER-01', expiry: '30 Nov 2026', quantity: 24, reserved: 0 },
    { id: 'stock-y-med', tenantId, locationId: 'Ward Y', itemId: 'item-med-1001', lotId: 'lot-ser-02', batch: 'SER-02', expiry: '30 Dec 2026', quantity: 0, reserved: 0 },
    { id: 'stock-central-cons', tenantId, locationId, itemId: 'item-cons-1001', lotId: null, batch: null, expiry: null, quantity: 6, reserved: 0 }
  ],
  transactions: [],
  requests: [],
  transfers: [],
  exceptions: [{ id: 'inventory-exception-1001', tenantId, locationId: 'Ward Y', type: 'Low Stock', itemId: 'item-med-1001', message: 'Ward Y has no available Sertraline stock.', status: UI9_STATUS.OPEN }],
  events: [],
  revision: 0
};
const storageKey = 'medixpro-ui9-domain-state';
function loadState() { try { const saved = typeof sessionStorage !== 'undefined' ? sessionStorage.getItem(storageKey) : null; return saved ? JSON.parse(saved) : structuredClone(initialState); } catch { return structuredClone(initialState); } }
let state = loadState();
let sequence = 0;
const listeners = new Set();
const emit = () => { state = { ...state, revision: state.revision + 1 }; if (typeof sessionStorage !== 'undefined') sessionStorage.setItem(storageKey, JSON.stringify(state)); listeners.forEach(listener => listener()); };
const nextId = prefix => { let id; do { id = `${prefix}-${++sequence}`; } while (Object.values(state).some(value => Array.isArray(value) && value.some(item => item?.id === id))); return id; };
const scoped = (access, item) => isTenantAllowed(access, item.tenantId || item.tenant) && isLocationAllowed(access, item.locationId || item.location);
const event = (id, type, title, recordId, sourceModule, client = null) => ({ id, type, title, date: now, recordId, sourceModule, clientId: client });
export function getUi9State() { return state; }
export function useUi9Store() { return useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener); }, getUi9State, getUi9State); }
export function getUi9VisibleRecords(access) { return Object.fromEntries(Object.entries(state).filter(([, value]) => Array.isArray(value)).map(([key, value]) => [key, value.filter(item => scoped(access, item))])); }
export function getItem(itemId) { return state.items.find(item => item.id === itemId); }
export function getStock(itemId, location) { return state.stockBalances.find(item => item.itemId === itemId && item.locationId === location); }
export function registerConfiguredItem(item) { const existing = state.items.find(value => value.id === item.id); const mapped = { id: item.id, itemCode: item.code, name: item.name, category: item.category, unitOfMeasure: item.unitOfMeasure, reorderLevel: item.reorderLevel, batchTrackingRequired: item.batchTrackingRequired, expiryTrackingRequired: item.expiryTrackingRequired, active: item.status !== 'Inactive' }; state.items = existing ? state.items.map(value => value.id === item.id ? { ...value, ...mapped } : value) : [...state.items, mapped]; emit(); return item.id; }
export function calculateInvoiceTotal(lines) { return lines.reduce((sum, line) => sum + Number(line.netAmount || 0), 0); }
export function createManualCharge(command) { if (!command?.serviceName || !command?.quantity || command.quantity <= 0 || command.unitPrice < 0) return null; const item = { id: nextId('charge'), tenantId, locationId: command.locationId || locationId, clientId: command.clientId || clientId, admissionId: command.admissionId || admissionId, serviceCode: command.serviceCode || 'MANUAL', serviceName: command.serviceName, serviceCategory: command.serviceCategory || 'Other', serviceDate: command.serviceDate || '20 Sep 2026', quantity: command.quantity, unitPrice: command.unitPrice, grossAmount: command.quantity * command.unitPrice, discount: command.discount || 0, tax: command.tax || 0, netAmount: command.quantity * command.unitPrice - (command.discount || 0) + (command.tax || 0), payerContext: command.payerContext || 'Self Pay', sourceModule: 'billing', sourceType: 'manual', sourceId: command.sourceId || null, status: UI9_STATUS.READY, createdAt: now, createdBy: command.actor || 'Billing User' }; state.charges = [...state.charges, item]; emit(); return item.id; }
export function createChargeFromSource(command) { if (!command?.sourceId || state.charges.some(item => item.sourceId === command.sourceId && item.status !== UI9_STATUS.CANCELLED)) return null; return createManualCharge({ ...command, sourceId: command.sourceId, sourceModule: command.sourceModule, sourceType: command.sourceType }); }
export function createDraftInvoice(chargeIds, command = {}) { const charges = chargeIds.map(id => state.charges.find(item => item.id === id)).filter(Boolean); if (!charges.length || charges.some(item => item.status === UI9_STATUS.INVOICED)) return null; const item = { id: nextId('invoice'), invoiceNumber: `INV-${Date.now().toString(36).toUpperCase()}`, tenantId, locationId: command.locationId || locationId, clientId: command.clientId || charges[0].clientId, admissionId: command.admissionId || charges[0].admissionId, payerContext: command.payerContext || charges[0].payerContext, chargeIds: charges.map(charge => charge.id), chargeLines: charges, subtotal: charges.reduce((sum, charge) => sum + charge.grossAmount, 0), discount: charges.reduce((sum, charge) => sum + charge.discount, 0), tax: charges.reduce((sum, charge) => sum + charge.tax, 0), total: calculateInvoiceTotal(charges), amountPaid: 0, balance: calculateInvoiceTotal(charges), status: UI9_STATUS.DRAFT, createdAt: now, createdBy: command.actor || 'Billing User', version: 1 }; state.invoices = [...state.invoices, item]; emit(); return item.id; }
export function finalizeInvoice(id, command = {}) { const item = state.invoices.find(invoice => invoice.id === id); if (!item || item.status !== UI9_STATUS.DRAFT || !item.chargeIds.length || state.charges.some(charge => item.chargeIds.includes(charge.id) && charge.status === UI9_STATUS.INVOICED)) return false; state.invoices = state.invoices.map(invoice => invoice.id === id ? { ...invoice, status: UI9_STATUS.ISSUED, finalizedAt: now, finalizedBy: command.actor || 'Billing User', issuedAt: now, issuedBy: command.actor || 'Billing User', version: invoice.version + 1 } : invoice); state.charges = state.charges.map(charge => item.chargeIds.includes(charge.id) ? { ...charge, status: UI9_STATUS.INVOICED, invoiceId: id } : charge); state.events = [...state.events, event(`invoice:${id}:issued`, 'Invoice Issued', `Invoice ${item.invoiceNumber} issued`, id, 'billing', item.clientId)]; emit(); return true; }
export function recordPayment(invoiceId, command = {}) { const invoice = state.invoices.find(item => item.id === invoiceId); const amount = Number(command.amount); if (!invoice || ![UI9_STATUS.ISSUED, UI9_STATUS.OPEN, UI9_STATUS.PAID].includes(invoice.status) || amount <= 0 || amount > invoice.balance || (command.reference && state.payments.some(payment => payment.invoiceId === invoiceId && payment.reference === command.reference))) return null; const payment = { id: nextId('payment'), invoiceId, tenantId: invoice.tenantId, locationId: invoice.locationId, clientId: invoice.clientId, admissionId: invoice.admissionId, amount, method: command.method || 'Bank Transfer', reference: command.reference || '', receivedAt: now, receivedBy: command.actor || 'Billing User' }; state.payments = [...state.payments, payment]; state.invoices = state.invoices.map(item => item.id === invoiceId ? { ...item, amountPaid: item.amountPaid + amount, balance: item.balance - amount, status: item.balance - amount === 0 ? UI9_STATUS.PAID : UI9_STATUS.OPEN } : item); state.events = [...state.events, event(`payment:${payment.id}:recorded`, 'Payment Recorded', `Payment ${payment.id} recorded`, payment.id, 'billing', payment.clientId)]; emit(); return payment.id; }
export function createAdjustment(invoiceId, command = {}) { const invoice = state.invoices.find(item => item.id === invoiceId); const amount = Number(command.amount); if (!invoice || invoice.status === UI9_STATUS.DRAFT || amount <= 0 || !command.reason) return null; const adjustment = { id: nextId('adjustment'), invoiceId, tenantId: invoice.tenantId, locationId: invoice.locationId, clientId: invoice.clientId, amount, reason: command.reason, type: command.type || 'Credit', createdAt: now, createdBy: command.actor || 'Billing User' }; state.adjustments = [...state.adjustments, adjustment]; state.invoices = state.invoices.map(item => item.id === invoiceId ? { ...item, balance: Math.max(0, item.balance - amount) } : item); emit(); return adjustment.id; }
export function voidInvoice(invoiceId, reason, command = {}) { const invoice = state.invoices.find(item => item.id === invoiceId); if (!invoice || !reason || invoice.status === UI9_STATUS.VOID || invoice.status === UI9_STATUS.PAID) return false; state.invoices = state.invoices.map(item => item.id === invoiceId ? { ...item, status: UI9_STATUS.VOID, voidReason: reason, voidedAt: now, voidedBy: command.actor || 'Billing User' } : item); state.events = [...state.events, event(`invoice:${invoiceId}:voided`, 'Invoice Voided', 'Invoice voided', invoiceId, 'billing', invoice.clientId)]; emit(); return true; }
export function receiveStock(command = {}) { if (!command.itemId || !command.locationId || command.quantity <= 0) return null; const existing = getStock(command.itemId, command.locationId); const transaction = { id: nextId('stock-tx'), transactionType: 'Receipt', tenantId, locationId: command.locationId, itemId: command.itemId, quantity: command.quantity, lotId: command.lotId || null, batch: command.batch || null, expiry: command.expiry || null, performedAt: now, performedBy: command.actor || 'Inventory User', reason: command.reason || 'Stock receipt' }; state.transactions = [...state.transactions, transaction]; if (existing) existing.quantity += command.quantity; else state.stockBalances = [...state.stockBalances, { id: nextId('stock'), tenantId, locationId: command.locationId, itemId: command.itemId, lotId: command.lotId || null, batch: command.batch || null, expiry: command.expiry || null, quantity: command.quantity, reserved: 0 }]; emit(); return transaction.id; }
export function issueStock(command = {}) { const stock = getStock(command.itemId, command.locationId); if (!stock || command.quantity <= 0 || stock.quantity - stock.reserved < command.quantity) return null; const transaction = { id: nextId('stock-tx'), transactionType: 'Issue', tenantId, locationId: command.locationId, itemId: command.itemId, quantity: command.quantity, sourceReference: command.sourceReference || null, performedAt: now, performedBy: command.actor || 'Inventory User', reason: command.reason || 'Stock issue' }; state.transactions = [...state.transactions, transaction]; stock.quantity -= command.quantity; emit(); return transaction.id; }
export function createStockRequest(command = {}) { if (!command.itemId || !command.fromLocationId || !command.toLocationId || command.fromLocationId === command.toLocationId || command.quantity <= 0) return null; const request = { id: nextId('stock-request'), tenantId, itemId: command.itemId, fromLocationId: command.fromLocationId, toLocationId: command.toLocationId, quantity: command.quantity, reason: command.reason || '', status: UI9_STATUS.REQUESTED, requestedBy: command.actor || 'Inventory User', requestedAt: now }; state.requests = [...state.requests, request]; emit(); return request.id; }
export function approveStockRequest(id, command = {}) { const request = state.requests.find(item => item.id === id); if (!request || request.status !== UI9_STATUS.REQUESTED) return false; state.requests = state.requests.map(item => item.id === id ? { ...item, status: UI9_STATUS.APPROVED, approvedBy: command.actor || 'Inventory User', approvedAt: now, approvedQuantity: Math.min(request.quantity, getStock(request.itemId, request.fromLocationId)?.quantity || 0) } : item); emit(); return true; }
export function issueStockTransfer(requestId, command = {}) { const request = state.requests.find(item => item.id === requestId); const quantity = command.quantity || request?.approvedQuantity; const stock = request && getStock(request.itemId, request.fromLocationId); if (!request || request.status !== UI9_STATUS.APPROVED || !quantity || !stock || stock.quantity < quantity) return null; stock.quantity -= quantity; const transfer = { id: nextId('transfer'), tenantId, itemId: request.itemId, fromLocationId: request.fromLocationId, toLocationId: request.toLocationId, requestedQuantity: request.quantity, approvedQuantity: quantity, issuedQuantity: quantity, receivedQuantity: 0, status: UI9_STATUS.ISSUED_STOCK, sourceRequestId: requestId, issuedBy: command.actor || 'Inventory User', issuedAt: now }; state.transfers = [...state.transfers, transfer]; state.requests = state.requests.map(item => item.id === requestId ? { ...item, status: quantity < item.quantity ? UI9_STATUS.PARTIAL : UI9_STATUS.FULFILLED } : item); emit(); return transfer.id; }
export function receiveStockTransfer(id, command = {}) { const transfer = state.transfers.find(item => item.id === id); if (!transfer || transfer.status !== UI9_STATUS.ISSUED_STOCK || transfer.receivedQuantity > 0) return false; const existing = getStock(transfer.itemId, transfer.toLocationId); if (existing) existing.quantity += transfer.issuedQuantity; else state.stockBalances = [...state.stockBalances, { id: nextId('stock'), tenantId, locationId: transfer.toLocationId, itemId: transfer.itemId, lotId: null, batch: null, expiry: null, quantity: transfer.issuedQuantity, reserved: 0 }]; state.transfers = state.transfers.map(item => item.id === id ? { ...item, receivedQuantity: item.issuedQuantity, status: UI9_STATUS.COMPLETED, receivedBy: command.actor || 'Inventory User', receivedAt: now } : item); emit(); return true; }
export function adjustStock(command = {}) { const stock = getStock(command.itemId, command.locationId); const delta = Number(command.delta); if (!stock || !delta || !command.reason || stock.quantity + delta < 0) return null; const transaction = { id: nextId('stock-tx'), transactionType: 'Adjustment', tenantId, locationId: command.locationId, itemId: command.itemId, quantity: delta, performedAt: now, performedBy: command.actor || 'Inventory User', reason: command.reason }; state.transactions = [...state.transactions, transaction]; stock.quantity += delta; emit(); return transaction.id; }
export function resetUi9Store() { if (typeof sessionStorage !== 'undefined') sessionStorage.removeItem(storageKey); state = structuredClone(initialState); sequence = 0; emit(); }
